### ISSUE TITLE
Minor warning found in log about origin_island

### ISSUE THREAD

**Issue by Hellcommander** [Glitchfiend/BiomesOPlenty#943] opened 2017-01-27 07:54 UTC
----
#### Issue Description:
warnings in the log file about
[Client thread/WARN]: No types have been added to Biome biomesoplenty:origin_island, types have been assigned on a best-effort guess: [PLAINS]

#### Steps to reproduce:

1. start game with biomes o plenty
2. wait til game loads
3. exit game and check the lastest.log

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log:
- Screenshots:

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: BiomesOPlenty-1.11-6.0.1.2137-universal.jar
- Minecraft: 1.11.2
- Forge: 13.20.0.2226

**Comment by GirafiStudios** [comment] 2017-01-27 07:56
Duplicate of https://github.com/Glitchfiend/BiomesOPlenty/issues/927.

**Closed** 2017-01-27 09:01 UTC
