### ISSUE TITLE
[1.8] Exception generating new chunk when using Agricultural Revolution Mod

### ISSUE THREAD

**Issue by Kiyaku** [Glitchfiend/BiomesOPlenty#591] opened 2016-01-08 22:00 UTC
Minecraft 1.8
Forge 11.14.4.1563
Biomes o Plenty (3.0.0.1505)
Agricultural Revolution (0.7.1)
Seed to test: "SeriousSeed"

Crashlog: http://pastebin.com/ksQqir3C

Traveling around generating new chunks can cause a crash once in a while. Loading the world after the crash seems fine, the chunk that crashed does not cause another crash, but other new generated chunks can. 

Changed the biome ids in the Agricultural Revolution mod so they won't match the biomes o plenty ones, but doesn't seem to make a difference. 

Also reported to Agricultural Revolution mod, but according to the crash log it seems like biomes o plenty is causing it?

Let me know if you need some more info!

Thanks!

**Comment by Adubbz** [comment] 2016-01-09 01:30
Hrm, couldn't reproduce this with the above setup. Do you know what the specific coords were where that issue happened? Did you disable any biomes or anything?

**Comment by Kiyaku** [comment] 2016-01-09 01:38
Unfortunately the coordinates seem to be different everytime, what it end to do is make the world (using the biomes o plenty world gen option, leaving it all on default) and just flying around. 

If i recreate the same world, different chunks would crash. 

I think in my tests i tend to fly east, slightly north (there should be some ocean north) and it eventually happens. Actually i wonder if it only happens near oceans (i believe both mods have coral stuff, not sure if that could cause it), i'm gonna have to double check this. 

Didn't change anything in the Biomes o plenty config but changed the ID's in the agricultural config (but even with default values it happens). But just in case, here is my the agricultural config: http://pastebin.com/xKjk5C9N 

Thanks for looking into this so far! :)

**Comment by Adubbz** [comment] 2016-01-09 02:00
Alright, should be fixed now. I copied the changes to the regular 1.8 branch too so both 1.8.9 and 1.8 should have the issue addressed

**Closed by Adubbz** 2016-01-09 02:00 UTC

**Comment by Kiyaku** [comment] 2016-01-09 05:03
Unfortunately the new version seems to crash when launching the game now (without any additional mods) :/

http://pastebin.com/YEwnxRwf

**Comment by Adubbz** [comment] 2016-01-09 10:03
Looks like I forgot to move the old files for our new build setup, should also *hopefully* be fixed now

**Comment by Kiyaku** [comment] 2016-01-09 10:49
Seems to work great, no crashes with agricultural mod either, thanks a lot! :D
