### ISSUE TITLE
BOP crashes minecraft

### ISSUE THREAD

**Issue by LlubNek** [Glitchfiend/BiomesOPlenty#654] opened 2016-02-03 12:40 UTC
Minecraft crashed shortly after entering a new world (as in, world created, player spawned, looked around, moved, then crashed).

I'm using BiomesOPlenty-1.8.9-3.0.0.1796-universal.jar.

Here's the crash report:
http://pastebin.com/N69QbWs1

Here's the log:
http://pastebin.com/bj9USgr5

**Comment by Adubbz** [comment] 2016-02-03 19:03
Does this occur without any other mods installed? In particular, by the looks of it, BuildCraft?

**Comment by LlubNek** [comment] 2016-02-03 21:47
No settings changed.  I'll try creating a world with the same seed without other mods and see what happens.  If this is related to worldgen of a particular biome it might not show up on any random seed.

**Comment by LlubNek** [comment] 2016-02-03 22:34
Not having any luck reproducing this crash.  Tried it with no other mods and with just buildcraft & BOP.
The seed I'm testing is 4347222442004717823.

**Comment by Adubbz** [comment] 2016-02-04 06:01
Yeah, my guess is it's a rare occurrence with some other mod installed. I'm not really seeing how it is possible for a -1 value to be used there without some kind of interference. If it's a major issue, I can add checks in to log an error rather than crashing (although I think it really should crash to be honest, this isn't something that should be possible). I'll close this for now but feel free to reopen it if you manage to track down the cause/reproduce it reliably

**Closed by Adubbz** 2016-02-04 06:01 UTC
