### ISSUE TITLE
Detected setBlock in a far chunk (flesh_tendon)

### ISSUE THREAD

**Issue by Kenpari** [Glitchfiend/BiomesOPlenty#2006] opened 2022-05-11 02:01 UTC
### What's the issue you encountered?

I was moving through the nether and just happened to be looking at the server console when I noticed this spamming the console:

[10May2022 21:20:38.217] [Worker-Main-204/ERROR] [net.minecraft.Util/]: Detected setBlock in a far chunk [-36, -20], pos: BlockPos{x=-565, y=94, z=-307}, status: minecraft:features, currently generating: ResourceKey[minecraft:worldgen/placed_feature / biomesoplenty:flesh_tendon]
[10May2022 21:20:38.217] [Worker-Main-204/ERROR] [net.minecraft.Util/]: Detected setBlock in a far chunk [-36, -20], pos: BlockPos{x=-565, y=94, z=-307}, status: minecraft:features, currently generating: ResourceKey[minecraft:worldgen/placed_feature / biomesoplenty:flesh_tendon]
[10May2022 21:20:38.217] [Worker-Main-204/ERROR] [net.minecraft.Util/]: Detected setBlock in a far chunk [-36, -20], pos: MutableBlockPos{x=-565, y=94, z=-307}, status: minecraft:features, currently generating: ResourceKey[minecraft:worldgen/placed_feature / biomesoplenty:flesh_tendon]

...And so on. Thousands of lines of it. The debug.log is rapidly becoming very large. It seems to only happen when I'm at certain parts of the nether, and every single one of them indicates flesh_tendon in similar/same chunks/coords. It's happened at least two distinct times in the logs, coinciding with two different points at which I was exploring the nether.

### How can the issue be reproduced?

Fly around the nether a bit and observe the server console/debug log. 

### Logs

https://gist.github.com/Kenpari/3ff0aaa652d7e28c54a2787a2c6fbde6 https://gist.github.com/Kenpari/01ae6b14b162d6c3233b0a4e56a5833b

### Mod Version

16.0.0.109

### Additional information

I am running on Forge version 40.1.19 for Minecraft 1.18.2. The server only has Biomes O' Plenty and Terrablender installed and is using a freshly generated world, generated only with these two mods. I've attached both the debug.log and latest.log.

**Comment by CorgiTaco** [comment] 2022-05-11 02:29
For context, this warning is thrown if a feature that's generating exceeds the neighbor chunk's boundary. The feature stage of world generation gives the chunk generating a chunk radius of 1, or a total area of 3x3 chunks

**Comment by ncottrill** [comment] 2022-05-30 05:06
Our server also reports a long series (spammed message) on this same item:

[29.05 22:04:14] [Server] [Worker-Main-32/ERROR] [minecraft/Util]: Detected setBlock in a far chunk [-3, -27], pos: BlockPos{x=-42, y=32, z=-431}, status: minecraft:features, currently generating: ResourceKey[minecraft:worldgen/placed_feature / biomesoplenty:flesh_tendon]
[29.05 22:04:14] [Server] [Worker-Main-32/ERROR] [minecraft/Util]: Detected setBlock in a far chunk [-3, -27], pos: BlockPos{x=-42, y=32, z=-431}, status: minecraft:features, currently generating: ResourceKey[minecraft:worldgen/placed_feature / biomesoplenty:flesh_tendon]
[29.05 22:04:14] [Server] [Worker-Main-32/ERROR] [minecraft/Util]: Detected setBlock in a far chunk [-3, -27], pos: BlockPos{x=-42, y=33, z=-431}, status: minecraft:features, currently generating: ResourceKey[minecraft:worldgen/placed_feature / biomesoplenty:flesh_tendon]
[29.05 22:04:14] [Server] [Worker-Main-32/ERROR] [minecraft/Util]: Detected setBlock in a far chunk [-3, -27], pos: BlockPos{x=-42, y=33, z=-431}, status: minecraft:features, currently generating: ResourceKey[minecraft:worldgen/placed_feature / biomesoplenty:flesh_tendon]
[29.05 22:04:14] [Server] [Worker-Main-32/ERROR] [minecraft/Util]: Detected setBlock in a far chunk [-3, -27], pos: BlockPos{x=-42, y=33, z=-431}, status: minecraft:features, currently generating: ResourceKey[minecraft:worldgen/placed_feature / biomesoplenty:flesh_tendon]
[29.05 22:04:14] [Server] [Worker-Main-32/ERROR] [minecraft/Util]: Detected setBlock in a far chunk [-3, -27], pos: BlockPos{x=-42, y=33, z=-431}, status: minecraft:features, currently generating: ResourceKey[minecraft:worldgen/placed_feature / biomesoplenty:flesh_tendon]
[29.05 22:04:14] [Server] [Worker-Main-32/ERROR] [minecraft/Util]: Detected setBlock in a far chunk [-3, -27], pos: BlockPos{x=-43, y=33, z=-430}, status: minecraft:features, currently generating: ResourceKey[minecraft:worldgen/placed_feature / biomesoplenty:flesh_tendon]
[29.05 22:04:14] [Server] [Worker-Main-32/ERROR] [minecraft/Util]: Detected setBlock in a far chunk [-3, -27], pos: BlockPos{x=-43, y=34, z=-430}, status: minecraft:features, currently generating: ResourceKey[minecraft:worldgen/placed_feature / biomesoplenty:flesh_tendon]
[29.05 22:04:14] [Server] [Worker-Main-32/ERROR] [minecraft/Util]: Detected setBlock in a far chunk [-3, -27], pos: BlockPos{x=-43, y=34, z=-430}, status: minecraft:features, currently generating: ResourceKey[minecraft:worldgen/placed_feature / biomesoplenty:flesh_tendon]
[29.05 22:04:14] [Server] [Worker-Main-32/ERROR] [minecraft/Util]: Detected setBlock in a far chunk [-3, -27], pos: BlockPos{x=-43, y=34, z=-430}, status: minecraft:features, currently generating: ResourceKey[minecraft:worldgen/placed_feature / biomesoplenty:flesh_tendon]
[29.05 22:04:14] [Server] [Worker-Main-32/ERROR] [minecraft/Util]: Detected setBlock in a far chunk [-3, -27], pos: BlockPos{x=-43, y=34, z=-430}, status: minecraft:features, currently generating: ResourceKey[minecraft:worldgen/placed_feature / biomesoplenty:flesh_tendon]

**Comment by ghost** [comment] 2022-05-30 11:27
Im having this promlem too.
The problem is because of this spamming my logfiles are nearly useless.

Application: Server
Operating System: Ubuntu 22.04
Java: openjdk-18-jre-headless
Minecraft: 1.18.2
Forge: 40.1.25
Mod Version: 16.0.0.109

**Comment by TheonlyTazz** [comment] 2022-06-30 11:26
I have found that this actually happens when moving towards an Erupting Inferno biome, but the Flesh Tendons actually belong to a Visceral Heap biome.

**Comment by MarbleGateKeeper** [comment] 2022-11-30 00:47
Confirms. It causes serious lag spike when enter nether.

**Comment by Adubbz** [comment] 2022-12-03 05:39
Closing in favour of #2048

**Closed as completed by Adubbz** 2022-12-03 05:39 UTC
Labels: bug
