### ISSUE TITLE
Strange ordinal-based crash

### ISSUE THREAD

**Issue by Sunconure11** [Glitchfiend/BiomesOPlenty#1318] opened 2018-10-06 00:42 UTC
--------------------------------------------------------------------------------

**BEFORE SUBMITTING!**

You must ensure the following before reporting an issue with the mod.
For feature requests, you may delete this template and create your own.

--------------------------------------------------------------------------------

- [x] Biomes O' Plenty is updated to the latest available version.
- [x] This issue occurs with Minecraft 1.12. 

**We *DO NOT* support Minecraft versions 1.7.10, 1.8.9, 1.9.4, 1.10.2, 1.11 or anything below that!**  

**YOUR ISSUE WILL AUTOMATICALLY BE CLOSED IF IT IS PERTAINING TO THOSE VERSIONS!**

--------------------------------------------------------------------------------

- [X] Forge is updated to the latest available version.

- [X] This issue occurs *WITHOUT* Optifine, Sponge or similar mods installed.

**Mods such as Optifine and Sponge interfere with the normal functioning of the game by modifying its code.**

**We do not support these mods in any way as they can introduce bugs which would not normally be present with**
**only Forge installed.**

--------------------------------------------------------------------------------

- [ ] This issue can be reproduced with ONLY Biomes O' Plenty and any other affected mods.

- [X] All other mods which appear to be involved are updated to their latest versions.

- [X] I have included any relevant logs and screenshots below.

**If this is a compatibility issue with another mod, you *MUST* test with *ONLY* Biomes O' Plenty and that specific mod.**

**Logs containing masses of mods are extremely unhelpful, and it is unlikely that your issue will be addressed.**

--------------------------------------------------------------------------------

- [ ] This issue does not occur in a modpack. 

**Issues with modpacks should be reported to the modpack author(s). As noted above, mod compatibility issues must**
**occur with the latest versions of both Biomes O' Plenty and the affected mod.** 

**The issue *MUST* be tested with *ONLY* Biomes O' Plenty and the affected mod.**

--------------------------------------------------------------------------------

*Once you have read and verified the above, you may delete all text up to this point.*

#### Issue Description:

Strange crash that I am not sure what exactly caused it, but it fired upon usage of a compass from Nature's Compass.

https://paste.dimdev.org/yifucejina.mccrash

#### Steps to reproduce:

1. I'm legitimately unsure, I used a compass from nature's compass to test an unrelated bug from another mod, to see if it was gone, and ran into this.
2. 
3. 

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log: 
- Screenshots:

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty:  7.0.1.2402
- Minecraft: 1.12.2
- Forge: 2765

**Comment by Robijnvogel** [comment] 2018-10-08 13:30
Related to #983 
This could be caused by another mod messing with `net.minecraft.world.gen.layer.IntCache.resetIntCache#`.

**Comment by Robijnvogel** [comment] 2018-10-08 13:39
No, it almost **must** be caused by that. I had Fulcanelli use a custom BoP build that prints the exact array that it fetched the climate ordinal that was out of bounds from. [When it crashed](https://paste.dimdev.org/bibocubita.mccrash), the specific value (248) could not be found in the printed array. It did contain a bunch of other values, though.

So I guess that some other concurrent process must be editing the array, the "int cache" that was obtained from the `IntCache` class.

**Comment by Robijnvogel** [comment] 2018-10-08 14:02
Is [this](https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.12.x-7.0.x/src/main/java/biomesoplenty/common/world/BiomeProviderBOPHell.java#L44) a good idea?

I actually think that [Coherent Villages](https://github.com/TheExceptionist/Coherent-Villages/search?q=resetIntCache&unscoped_q=resetIntCache) may be connected to this.

**Comment by Forstride** [comment] 2019-05-25 07:22
Closing this because we either can't/won't fix it or it's not an issue in 1.13

**Closed by Forstride** 2019-05-25 07:22 UTC

**Comment by Barteks2x** [comment] 2019-10-26 16:26
Just for someone maybe reading this in the future, this is very likely to be caused by vanilla bug and fixed in latest 1.12.x forge build with https://github.com/MinecraftForge/MinecraftForge/pull/5720 (forge build 2844, also fixed by Mojang in 1.13+)
