### ISSUE TITLE
Pus Bubble Crashing server

### ISSUE THREAD

**Issue by IDEZIHREE** [Glitchfiend/BiomesOPlenty#1892] opened 2021-08-14 22:46 UTC
Bug Report

Entity collides with Pus bubble block and crashes server

How can the crash be reproduced?

Anytime someone is in the nether (mostly with multiple people) the server crashes due to entity colliding with block. We never see this happen I just read it in the crash logs to know

 Crash Report and Logs
I do not know if this helps I suck with code but it can be any mod that collides with the block

java.lang.NoSuchMethodError: 'void biomesoplenty.common.block.PusBubbleBlock.spawnParticles(net.minecraft.world.level.Level, net.minecraft.core.BlockPos)'
	at biomesoplenty.common.block.PusBubbleBlock.m_7892_(PusBubbleBlock.java:87) ~[BiomesOPlenty-1.17.1-14.0.0.32-universal.jar%2323!:1.17.1-14.0.0.32] {re:classloading,pl:runtimedistcleaner:A}### Mod Version

Mod Version
1.17.1

**Comment by Forstride** [comment] 2021-08-14 22:58
Whoops, probably shouldn't have added the client-sided annotation for that.  Anyway, should be fixed in the next build that goes up

**Closed by Forstride** 2021-08-14 22:58 UTC
Labels: crash

**Comment by IDEZIHREE** [comment] 2021-08-14 23:02
Should I just wait then? didnt know if I could do anything just cause its unplayable and should i delete this post if i put something bad?

**Comment by Forstride** [comment] 2021-08-14 23:09
Huh?  No, I fixed the issue.  I was just explaining what the issue was caused by.

**Comment by IDEZIHREE** [comment] 2021-08-14 23:21
Oh okay sorry I didn't understand that you already had fixed it thanks
