### ISSUE TITLE
Incompatible Mods

### ISSUE THREAD

**Issue by ShootToKillSTK** [Glitchfiend/BiomesOPlenty#1809] opened 2021-02-14 03:44 UTC
Biomes o plenty preset makes Biomes you go mod not spawn biomes in end or nether

Latest BoP version used, Forge 35.1.28

**Comment by Forstride** [comment] 2021-02-14 04:49
Duplicate of https://github.com/Glitchfiend/BiomesOPlenty/issues/1755

**Closed by Forstride** 2021-02-14 04:49 UTC
Labels: bug-minor
