### ISSUE TITLE
conflict with BuildCraft

### ISSUE THREAD

**Issue by Hypsellis** [Glitchfiend/BiomesOPlenty#1041] opened 2017-06-07 10:22 UTC
There is a conflict between BOP 6.1.0.2239 and upper versions and BuildCraft which causes Minecraft to crash when creating a world https://pastebin.com/3kiPeg42

**Comment by Hypsellis** [comment] 2017-06-07 10:22
https://github.com/BuildCraft/BuildCraft/issues/3657

**Comment by Forstride** [comment] 2017-06-07 12:40
Ok, a few things to try:

1) Do you have any biomes disabled?  If so, which ones?

2) Try deleting your config files for BOP and try generating a new world.  It might have something to do with the White Beach biome being added recently.

**Comment by Hypsellis** [comment] 2017-06-07 16:23
Ok I deleted the config file, and now it works, thanks for the advice. ;)

**Comment by Hypsellis** [comment] 2017-06-08 07:56
Ok it doesn't work, I had forgotten to precise I wanted to use the BOP world generation when creating the world. The crash occurs at each time I try to create a world with BOP world generation. Delete the config file doesn't change anything. :(

**Comment by AEnterprise** [comment] 2017-06-08 08:05
BC will no longer crash in the next version due to invalid biome id's but this is still an issue because oil will not generate and i assume alot of other mods their world generators and biome dependant decorators will not trigger

**Comment by Adubbz** [comment] 2017-06-08 08:49
What is the most recent version of BoP that doesn't crash for you? Also did you disable any biomes, as per Forstride's question?

I'm a tad confused how you went from deleting the config file does work to not working... The original issue did state when creating a world...

**Comment by Hypsellis** [comment] 2017-06-08 14:55
It crashes since the adding of the white beach. Forstride had suggested me to delete the config maybe because the config hadn't updated it and hadn't integrated the white beach biome. I thought it worked at first before I realize I hadn't chosen BOP generation when creating a new world, and then I got the crash again. I didn't disabled any biomes.

**Comment by Adubbz** [comment] 2017-06-10 03:25
Can't reproduce this at all with just BoP and Buildcraft 7.99.4 (released on May the 30th, prior to any fixes). I can only assume some other mod is interfering, because BoP on its own would have issues were any biome ids set to -1 (or at the very least, there'd be log spam about it).

Given that they've implemented a workaround, I'm gonna close this. This isn't the sort of issue where we can just blindly take a stab in the dark, so there's not really much we can do here. And even then, it may not necessarily even be us, it may be a mod that's making assumptions that aren't always true.

**Closed by Adubbz** 2017-06-10 03:25 UTC

**Comment by AEnterprise** [comment] 2017-06-10 07:07
One thing we noted in the past about this issue when testing with BC is that it also heapened with just BC but because some kind of edge case in vanilla/forge that seemed to trigger biome generation on the client side

**Comment by Hypsellis** [comment] 2017-06-10 14:23
The problem isn't solved, the issue still happens. https://pastebin.com/HXvhd4Q6

**Comment by AEnterprise** [comment] 2017-06-10 14:51
@Hypsellis it still heapens because we have not yet released a new BC version containing the workaround, it will be in 7.99.5

**Comment by Swornh** [comment] 2017-06-10 23:56
Oh ok, lets wait for the BC then.
