### ISSUE TITLE
Undergrowth generates bushes above the bedrock ceiling

### ISSUE THREAD

**Issue by LoftyLoftyLoftyLoftyLofty** [Glitchfiend/BiomesOPlenty#2070] opened 2023-01-02 01:37 UTC
### What's the issue you encountered?

Bushes and other misc clutter are being generated above the bedrock ceiling in Undergrowth and other BOP nether biomes.

### How can the issue be reproduced?

Visit the nether. Look above the ceiling.

### Mod Version

1.19.2-17.1.1.162

**Comment by Forstride** [comment] 2023-02-17 16:46
Duplicate of #1980

**Closed as completed by Forstride** 2023-02-17 16:46 UTC
Labels: bug
