### ISSUE TITLE
[1.8] BOP bamboo drops blocks with secondary item information

### ISSUE THREAD

**Issue by croftyraider** [Glitchfiend/BiomesOPlenty#546] opened 2015-09-25 00:37 UTC
![bop bamboo issue](https://cloud.githubusercontent.com/assets/7588838/10090311/f114a3c0-62e2-11e5-9611-24b0516bd1af.png)

**Comment by Adubbz** [comment] 2015-12-16 00:16
I can't reproduce this with naturally generated bamboo or player-placed bamboo. In case you were referring to thatching, I also tested that without any issues either. Middle-clicking also doesn't appear to cause this issue with either. Please test again with the latest version of BoP and Forge for 1.8 without any other mods.

**Comment by Adubbz** [comment] 2016-01-04 13:22
Closing this unless it can be confirmed

**Comment by croftyraider** [comment] 2016-01-04 20:00
Trivially reproduced for me with the version of BOP I was using --1.8-3.0.0.1389 with forge 11.14.3.1543 (minecraft 1.8). I just put down some bamboo, then put a few on top of the ones touch dirt, then punched a few at random and one of them popped up looking like this:

![bop-bug](https://cloud.githubusercontent.com/assets/7588838/12099039/b6ccf2b0-b2da-11e5-9072-bb9811f92dc7.jpg)

**Comment by Adubbz** [comment] 2016-01-05 21:46
Does this still occur on the latest version? It's likely we may have just fixed it unintentionally in builds made after the one you're using

**Comment by croftyraider** [comment] 2016-01-06 02:30
Yes it does. I tried it with the 1.8.9-3.0.0.1603 version of BOP using forge 1.8.9-11.15.0.1684

What I did, in creative mode, is grab a bamboo and plant a bunch, stacking a few. Then I switched to survival and started punching the upper pieces (not the bottom one touching the dirt). Started getting some of those unknown blocks. Turned on F3-H and saw that they were bamboo but with a number following the item id.

**Comment by Adubbz** [comment] 2016-01-06 06:19
Ah, okay, I think I know what you mean now - Sounds like it's a similar issue to saplings which I fixed yesterday

**Comment by Adubbz** [comment] 2016-01-06 06:26
Ah, okay, I can reproduce this now. As you said, it's about the age property being above 0. Fixing it now

**Comment by Adubbz** [comment] 2016-01-06 06:31
Should be fixed now. Let me know if there's any more issues. Apologies for my initial slow response, I haven't had the chance to look at BoP stuff properly until now.

**Closed by Adubbz** 2016-01-06 06:31 UTC
Labels: 1.8.9, bug-minor
