### ISSUE TITLE
Nether Biomes generate with standard world type, but decorator does not run

### ISSUE THREAD

**Issue by 666lumberjack** [Glitchfiend/BiomesOPlenty#1213] opened 2018-03-23 17:24 UTC
#### Issue Description:
When creating a world with the standard worldtype, BoP biomes still generate in the Nether. However, they consist of only surface blocks with no decoration - vines, flowers, wasp hives, fire in ash biomes etc. 

#### Steps to reproduce:

1. Create new world with the standard worldtype
2. Enter the nether
3. Find a BoP biome and observe lack of decoration

#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 7.0.1.2334
- Minecraft: 1.12.2
- Forge: tested on 2611 & 2632

**Comment by Forstride** [comment] 2018-03-23 17:32
Can't reproduce this at all.  Decoration is working just fine for me.

If you are using other mods that affecting terrain/Nether generation, that might be affecting it.

**Comment by 666lumberjack** [comment] 2018-03-23 20:48
I am using no other mods. You definitely tested with standard worldtype and not BoP? BoP worlds generate fine.

**Comment by Forstride** [comment] 2019-05-25 07:15
Closing this because we either can't/won't fix it or it's not an issue in 1.13

**Closed by Forstride** 2019-05-25 07:15 UTC
Labels: bug-minor
