### ISSUE TITLE
Beta 2402 - Ticking Entity Crash

### ISSUE THREAD

**Issue by Excaliburning** [Glitchfiend/BiomesOPlenty#1324] opened 2018-10-16 22:05 UTC
#### Issue Description:

Ticking Entity crash, BoP crashed the server but the entity which got ticked is a Rocket Creeper from Primitive Mobs.
[Crash Log here.](https://gist.github.com/Excaliburning/68c3c33ab50eee54be6c9000da2972e1)

#### Steps to reproduce:

No idea, a friend reported the crash to me, I went to check if there was a crash log.
Seems like an isolated issue.
Update: It seems to crash whenever a Rocket Creeper (from Primitive Mobs) explodes in a BoP biome.

____
#### Affected Versions :

- Biomes O' Plenty: BiomesOPlenty-1.12.2-7.0.1.2402 (beta release)
- Minecraft: 1.12.2
- Forge: 2768

**Comment by Excaliburning** [comment] 2018-10-19 11:39
[Another Crash Log](https://gist.github.com/Excaliburning/17b4c35733d5ab6b401f8c780dce743e)

**Comment by fisher521** [comment] 2018-11-17 02:09
Can reproduce. Crash log: https://pastebin.com/Sfxz1tvJ

**Comment by CaseyLoufek** [comment] 2018-12-10 22:14
It's caused by the Rocket Creeper's explosion interacting with BoP dirt, which is weird since the explosion code seems fairly vanilla and the vanilla Creepers don't seem to have an issue.

Also replicability is intermittent, about 50% of RC explosions cause crashes for me.

[crash-2018-12-10_12.36.14-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/2665153/crash-2018-12-10_12.36.14-server.txt)
[crash-2018-12-10_11.35.03-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/2665154/crash-2018-12-10_11.35.03-server.txt)
[crash-2018-12-10_11.41.01-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/2665155/crash-2018-12-10_11.41.01-server.txt)

**Comment by Forstride** [comment] 2019-05-25 07:25
Closing this because we either can't/won't fix it or it's not an issue in 1.13

**Closed by Forstride** 2019-05-25 07:25 UTC

**Comment by CaseyLoufek** [comment] 2019-05-25 08:49
This was actually resolved on Primitive Mob's end a few versions ago. Sorry I forgot to update here.
