### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by Killaheala** [Glitchfiend/BiomesOPlenty#889] opened 2016-11-08 02:32 UTC
![Uploading 2016-11-07_21.32.47.png…]()
![Uploading 2016-11-07_21.32.49.png…]()

MC: 1.10.2
Forge: 2121
Biomes O Plenty: 2091 
Texture Packs: Soartex Fanver / Dramatic Skies / Tinker Sphax / EnderIO Demodelization
           
Missing Textures on Maple leaves, all walls and all fences, except for fence doors.

**Comment by GirafiStudios** [comment] 2016-11-08 02:34
As you said yourself you are using multiple texturepacks, so it is caused by one of them.
Biomes O' Plenty have no missing textures at all.

**Comment by Killaheala** [comment] 2016-11-08 02:38
Fixed, thanks
![2016-11-07_21 37 41](https://cloud.githubusercontent.com/assets/20982732/20084749/735248b4-a532-11e6-9b74-a5b671a900e3.png)

**Comment by GirafiStudios** [comment] 2016-11-08 02:39
Great :)
Could you please close this then @Killaheala?

**Closed** 2016-11-08 02:48 UTC
