### ISSUE TITLE
Crash when entering nether

### ISSUE THREAD

**Issue by Y0da1** [Glitchfiend/BiomesOPlenty#416] opened 2015-02-27 17:49 UTC
Hi! I tried today to add BiomesOPlenty to my modpack. Everything works fine in the overworld, but when I enter the nether, the console spams and a few seconds later the game crashes.

The first crash:
http://pastebin.com/Z4N2uvDX

The other ones(after I removed some nether biomes and OptiFine)
http://pastebin.com/c8d07HwN

Logs: https://www.dropbox.com/s/tfll71vic385xn3/logs.rar?dl=0(it didnt let me upload them on pastebin)
VirusTotal link: https://www.virustotal.com/ro/file/f357b6193547637e588df0373b32643550338d3c360a79477073f3fe4740a17c/analysis/1425059277/

My biome configuration: http://pastebin.com/kJ8a1a8c

**Comment by wwrpg** [comment] 2015-05-14 18:01
I think this issue is fixed in the latest version. The crash was caused by a fluid contact causing an invalid block update in the world.java. I tested all the BOP fluids I could in the nether, and saw no issues

**Closed** 2016-02-02 21:41 UTC
