### ISSUE TITLE
Server tick loop error

### ISSUE THREAD

**Issue by ZandercraftGames** [Glitchfiend/BiomesOPlenty#1308] opened 2018-09-08 03:54 UTC
--------------------------------------------------------------------------------

**BEFORE SUBMITTING!**

You must ensure the following before reporting an issue with the mod.
For feature requests, you may delete this template and create your own.

--------------------------------------------------------------------------------

- [X] Biomes O' Plenty is updated to the latest available version.
- [X] This issue occurs with Minecraft 1.12. 

**We *DO NOT* support Minecraft versions 1.7.10, 1.8.9, 1.9.4, 1.10.2, 1.11 or anything below that!**  

**YOUR ISSUE WILL AUTOMATICALLY BE CLOSED IF IT IS PERTAINING TO THOSE VERSIONS!**

--------------------------------------------------------------------------------

- [X] Forge is updated to the latest available version.

- [X] This issue occurs *WITHOUT* Optifine, Sponge or similar mods installed.

**Mods such as Optifine and Sponge interfere with the normal functioning of the game by modifying its code.**

**We do not support these mods in any way as they can introduce bugs which would not normally be present with**
**only Forge installed.**

--------------------------------------------------------------------------------

- [X] This issue can be reproduced with ONLY Biomes O' Plenty and any other affected mods.

- [X] All other mods which appear to be involved are updated to their latest versions.

- [X] I have included any relevant logs and screenshots below.

**If this is a compatibility issue with another mod, you *MUST* test with *ONLY* Biomes O' Plenty and that specific mod.**

**Logs containing masses of mods are extremely unhelpful, and it is unlikely that your issue will be addressed.**

--------------------------------------------------------------------------------

- [X] This issue does not occur in a modpack. 

**Issues with modpacks should be reported to the modpack author(s). As noted above, mod compatibility issues must**
**occur with the latest versions of both Biomes O' Plenty and the affected mod.** 

**The issue *MUST* be tested with *ONLY* Biomes O' Plenty and the affected mod.**

--------------------------------------------------------------------------------

*Once you have read and verified the above, you may delete all text up to this point.*

#### Issue Description:
When my forge client gets to the screen: "Generating World..." it gets to 12 percent then Minecraft crashes returning the error:
`The game crashed whilst exception in server tick loop
The game crashed whilst exception in server tick loop
Error: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class biomesoplenty.common.block.BlockBOPGrass$BOPGrassType, values=[spectral_moss, overgrown_stone, loamy, sandy, silty, origin, overgrown_netherrack, daisy, mycelial_netherrack]} as it does not exist in BlockStateContainer{block=minecraft:grass, properties=[snowy]}`

#### Steps to reproduce:

1. Install latest forge version
2. Put BOP in mods folder
3. Launch minecraft forge
4. Create a new world with the BOP world generator
5. Try to open world
6. Game crashes

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: BiomesOPlenty-1.12.2-7.0.1.2399
- Minecraft: 1.12.2
- Forge: 1.12.2 - 14.23.4.2759 and 1.12.2 - 14.23.4.2705

**Comment by GirafiStudios** [comment] 2018-10-03 22:20
Cannot reproduce, with exact same versions of BoP and Forge.

**Comment by Forstride** [comment] 2019-05-25 07:22
Closing this because we either can't/won't fix it or it's not an issue in 1.13

**Closed by Forstride** 2019-05-25 07:22 UTC
