### ISSUE TITLE
[1.7.10] Rendering issue with AMD graphics in certain biomes

### ISSUE THREAD

**Issue by NEXUS2345** [Glitchfiend/BiomesOPlenty#441] opened 2015-03-31 23:01 UTC
When entering certain biomes (temperate rainforest and several others) on version 2.1.0.1164 with AMD graphics cards and graphics set to fast, the screen turns almost black and misrenders most blocks and items.

Images to back up: http://imgur.com/7i3K1x2,9AyTF8D,JIgKhlT
Video 1: waiting for upload
Video 2: waiting for upload

**Comment by StenchBag** [comment] 2015-04-03 12:29
I'm getting this too but on intel HD graphics

**Comment by Adubbz** [comment] 2015-04-03 12:55
Could I get a full list of the biomes this happens in? This looks like a major bug that warrants quickly revisiting 1.7. I suspect this may be happening as a result of the new fog changes by @jaquadro.

**Comment by jaquadro** [comment] 2015-04-03 13:26
@Adubbz perhaps you could try testing this with fast graphics to help establish if it's a graphics mode or GPU problem?

I have an Intel HD laptop I can drag home later to try it on.  But if it's an AMD issue .. well I switched to nVidia a while ago.

**Comment by NEXUS2345** [comment] 2015-04-03 13:28
I have NVIDIA graphics and I do not suffer from the issue, I have had players on a server I admin test it and only the ones with AMD graphics suffer from this issue. I will work on getting a full list of biomes but it may be a bit difficult and could take some time.

**Comment by NEXUS2345** [comment] 2015-04-03 16:13
I can confirm however that it is happening in the overworld-like Nether biome and the Temperate rainforest, those are the only ones I know of so far...

**Comment by jaquadro** [comment] 2015-04-03 17:27
All the biomes I know of with special fog settings are: Arctic, Bamboo Forest, Bayou, Crag, Dead Swamp, Fen, Frost Forest, Mystic Grove, Ominous Woods, Polar Chasm, Seasonal Forest, Sludge Pit, Temperate Rainforest, Tropical Rainforest, Wasteland

**Comment by StenchBag** [comment] 2015-04-03 17:53
Sludgepit, Fen and Seasonal Forest are a few.

**Comment by jaquadro** [comment] 2015-04-03 19:28
There's a config line in biomesoplenty/misc.cfg: "Enable Fog Colors".  Can you set this to false and see if it changes any of the behavior?

I think it's more related to fog distance if anything, but it doesn't look like the handler does anything different than what Vanilla code already does.

**Comment by StenchBag** [comment] 2015-04-03 20:00
Yep, that fixed it.

**Comment by jaquadro** [comment] 2015-04-03 20:01
Interesting, but useful information.

Are you running this with other mods?  If you test BoP by itself on Vanilla, does it work with the fog colors turned on?

**Comment by StenchBag** [comment] 2015-04-03 20:09
The only other thing I ran with it was forge.

**Comment by NEXUS2345** [comment] 2015-04-03 20:18
We ran it with our modpack where people were having issues and disabling Fog Color does fix the issue with the rendering. Thank you for finding a fix as we can now push this config change out to our modpack! Otherwise I hope you have luck fixing this bug.

**Comment by jaquadro** [comment] 2015-04-03 20:20
Glad you've got something to work with.  Please continue monitoring this issue, as I'll need your help to confirm any permanent fixes if I can't find a computer to reproduce it on.

**Comment by NEXUS2345** [comment] 2015-04-03 20:21
Ok, I get a notification whenever you post on here anyway so I will see if you need anything! :)

**Comment by NEXUS2345** [comment] 2015-04-03 20:22
Ok, I have been told to inform you that it only happens on 7000 and 2xx series AMD cards (the ones that use the GCN architecture).

**Comment by jaquadro** [comment] 2015-04-03 22:24
I dragged out my old beast with an HD 6850, but that's a revision before GCN.  Couldn't reproduce the issue with it.  Too bad I gave away my 7000 series card last month for what was ultimately a mainboard problem.

I was able to reproduce a different issue I saw posted on the forums -- totally messed up fog color (e.g. bright red in seasonal forest with no transition) with graphics settings set to 'fast'.  That's at least something to chew on.  If I can't find a good solution, bypassing fog color entirely in 'fast' mode sounds reasonable.

**Comment by jaquadro** [comment] 2015-04-03 23:08
I've submitted PR #446 to fix the fast graphics issue.  It may fix this one as well.

**Comment by Adubbz** [comment] 2015-04-03 23:21
Merged, hopefully it fixed it :)

**Comment by NEXUS2345** [comment] 2015-04-03 23:22
When can we expect it to be pushed to the full build?

**Comment by Adubbz** [comment] 2015-04-03 23:34
it's already up, Build 1.7.10-2.1.0.1174

**Comment by Adubbz** [comment] 2015-04-04 11:15
From what i've heard, this should be fixed now. If this isn't the case, feel free to reopen the issue.

**Closed by Adubbz** 2015-04-04 11:15 UTC
