### ISSUE TITLE
1.12 Chunk holes [Bug] 

### ISSUE THREAD

**Issue by Quizer9O8** [Glitchfiend/BiomesOPlenty#1064] opened 2017-07-01 10:09 UTC
Issue Description: 
Chunk holes do appear in BOP/Vanilla biomes, mostly in BOP biomes.
As far as I know, these chunk holes are most of the time ocean/deep ocean biomes but recently I've discovered that it can also be a BOP biome too.

Steps to reproduce:

1. Make a new world with Biomes O'Plenty selected
2. Fly around your world until you see something out of place 
    (Journeymap recommended for finding chunk holes easier) 

Additional Information:
Screenshots:
![2017-07-01_11 52 02](https://user-images.githubusercontent.com/19509275/27761079-cf73a106-5e55-11e7-9fbe-80a0a74c816f.png)
![2017-07-01_11 58 19](https://user-images.githubusercontent.com/19509275/27761080-cf73cff0-5e55-11e7-9b29-8522073bade4.png)
![2017-07-01_11 58 36](https://user-images.githubusercontent.com/19509275/27761078-cf7343be-5e55-11e7-84a3-af8c50e05913.png)
![2017-07-01_11 58 54](https://user-images.githubusercontent.com/19509275/27761081-cf73fa0c-5e55-11e7-801e-72a3387063da.png)
![2017-07-01_10 46 04](https://user-images.githubusercontent.com/19509275/27761082-cf741a82-5e55-11e7-8d65-fcbce29d24dc.png)

Affected Versions:

- Biomes O' Plenty: 1.12-7.0.0.2288
- Minecraft: 1.12
- Forge: 14.21.1.2387

**Comment by Adubbz** [comment] 2017-07-01 10:28
Does this happen with BoP on its own? Are any biomes disabled? And what's the seed?

**Comment by Quizer9O8** [comment] 2017-07-01 14:02
This does happen with Bop on it's own. Sadly I deleted the world.
All you have to do is fly around a little bit to see it for yourself.
I will look for a new seed in the meanwhile to see if I can recreate it myself.

**Comment by Forstride** [comment] 2017-07-01 15:07
I can't reproduce this at all, nor have I seen any chunk holes on my own.  You should probably try with just vanilla by itself, because AFAIK, chunk holes are generally linked to poor performance, and could happen regardless of the terrain generator.

**Comment by Quizer9O8** [comment] 2017-07-01 15:54
I have 16 gigs of memory in my pc. It quite strange because I always have this with BOP :(

**Comment by Forstride** [comment] 2017-07-01 15:59
RAM isn't the only thing that affects performance.  You're running the game with integrated graphics on your CPU, which is only clocked at 2.4 GHz.

**Comment by Quizer9O8** [comment] 2017-07-01 16:13
I have an AMD Radeon R7 M270 Processor. I doubt it's causing these chunk holes. 
I only have this with BOP, not ATG, RTG, etc... Do you need a log file?

**Comment by mankra** [comment] 2017-07-15 12:32
I've just tested the given seed with

- BOP 7.0.0.2289
- MC 1.12
- Forge 14.21.1.2412
- OptiFine HD-U-C4

in standard settings and I don't see any chunk holes.

**Comment by Quizer9O8** [comment] 2017-07-18 21:53
I can confirm that these chunk holes are totally random. I recreated a world that had one and after flying to the same location it wasn't to be found anywhere...

**Comment by Quizer9O8** [comment] 2017-07-28 14:03
I'm getting a little bit frustrated with this bug because it isn't the first time it occurred. It goes way back to 1.10.2. Some people claim it has to do something with poor CPU performance, RAM integrated graphics, bugs, glitches or any terrain generator itself. Yes any computer can cause abnormalities during gameplay but After a further analysis BOP seems to be the source of the problem.

Evidence 1:
![2017-07-28_14 56 23_better beginnings_overworld_day](https://user-images.githubusercontent.com/19509275/28719418-3381aa3a-73aa-11e7-8cf8-b5caa25e1256.png)
As you can see the terrain generator is set on Biomes O'Plenty and there are quite a majority of chunk holes present. This happens as soon as the world starts loading around the player or if you're pre-generating chunks.

Evidence 2:
![2017-07-28_15 24 40_copy of better beginnings_overworld_day](https://user-images.githubusercontent.com/19509275/28719693-20c88dfe-73ab-11e7-829c-37687ba5e47a.png)
This time I create a Default world (With BOP still enabled) and not so long after I found another chunk hole. So I decided to disable Biomes O'Plenty, recreate the world using the same seed and after generating chunks after 30 minutes this is the result I get...
![2017-07-28_15 22 40_copy of copy of better beginnin2_overworld_day](https://user-images.githubusercontent.com/19509275/28720016-42aef18c-73ac-11e7-8a51-098003f673cd.png)
No chunk holes in sight, so what does this mean?
I guess this has something to do with some faulty coding somewhere in the mod.
I have used and tested countless terrain generators in 1.10.2 -1.12 and I haven't seen this problem by any of them but BOP so could this bug be further investigated because I really love using this mod without any serious problems lingering that long whatsoever.

Here is a log file in case any of you need them...
https://pastebin.com/bYffE6Dm

**Comment by Forstride** [comment] 2017-07-28 18:44
BOP doesn't affect the default world type *at all*.  Did you test it more than once?  Because I guarantee that it's entirely random.

**Comment by Quizer9O8** [comment] 2017-07-28 19:32
Yes I did and it is entirely random but the chances of it ever happening are likely

**Comment by Forstride** [comment] 2018-03-02 01:37
Closing this, because no offense, but you seem to be the only person who has these chunk issues, and no one else can reproduce them.

**Closed by Forstride** 2018-03-02 01:37 UTC
