### ISSUE TITLE
Setting biome spawn odds

### ISSUE THREAD

**Issue by ArdiPINK** [Glitchfiend/BiomesOPlenty#1481] opened 2019-10-23 20:00 UTC
Is there a way to adjust the chance of occurrence for each biome? Very often the same biomes are written, 73 biomes are written, but after playing for a week I saw about 10, I would like to adjust the chances.

**Comment by Forstride** [comment] 2020-01-05 06:29
Closing as it's essentially a duplicate of #1397

**Closed by Forstride** 2020-01-05 06:29 UTC
