### ISSUE TITLE
Extreme lags on server with newest Forge (1.16.3-34.1.16)

### ISSUE THREAD

**Issue by CherryGirl3112** [Glitchfiend/BiomesOPlenty#1698] opened 2020-10-10 16:16 UTC
Does anyone else have enormous lags with 1.16.3 on a server?
Even if it's the only mod on the server?

In Singleplayer it runs smoothly with no lags.

**Comment by Forstride** [comment] 2020-10-10 18:20
Duplicate of https://github.com/Glitchfiend/BiomesOPlenty/issues/1682

**Closed by Forstride** 2020-10-10 18:20 UTC
Labels: bug-minor
