### ISSUE TITLE
Creating a world with a disabled biome causes a crash on world load

### ISSUE THREAD

**Issue by KnightMiner** [Glitchfiend/BiomesOPlenty#1037] opened 2017-06-05 03:39 UTC
#### Issue Description:

Attempting to create a world with a disabled biome causes a crash. I specifically disabled the alps biome.

#### Steps to reproduce:

1. Disable the alps biomes by setting its ID to -1.
2. Create a world using the Biomes O Plenty world generator type.
3. The game will freeze on "Loading world". Checking your game log will state the server state changed to stopped and a crash report is added to your crash reports folder, though the client never realizes the game crashed
4. Use command prompt or task manager to force kill Minecraft.

#### Additional Information:

[Crash report](https://pastebin.com/z1R42sAj)
____
#### Affected Versions:

- Biomes O' Plenty: 1.11.2-6.1.0.2238-universal
- Minecraft: 1.11.2
- Forge: 13.20.0.2313

**Comment by Adubbz** [comment] 2017-06-05 03:41
This is a duplicate of https://github.com/Glitchfiend/BiomesOPlenty/issues/1030

**Closed by Adubbz** 2017-06-05 03:41 UTC

**Comment by KnightMiner** [comment] 2017-06-05 03:49
Sorry, I did not look into that issue when it came up in my search due to the title being so different than my issue.

**Comment by Adubbz** [comment] 2017-06-05 03:50
No worries, it's not immediately obvious it's the same issue so it's completely understandable
