### ISSUE TITLE
Climate Lookup Fail

### ISSUE THREAD

**Issue by FallenEagle1** [Glitchfiend/BiomesOPlenty#1231] opened 2018-04-10 18:43 UTC
#### Issue Description:
Disclaimer, this comes from a user, so not firsthand knowledge.
This is running in the All the Mods 3 pack.
User is running into a crash that has happened multiple times to them. The time of the crash that was described to me was they were looking through Journey Maps and as they were scrolling through sections of the world the game crashed. Looking through the crash log it looks to be in this case that it is crashing on displaying a ic2 rubber tree (lines 53 and 54 of the crash log provided). This seemed somewhat similar to  #1029 but being minecraft 1.12.2, I figured it warranted a separate issue for it. Don't have access to the latest.log, I can ask to get those if needed if/when I hear about the world crashing again.

#### Steps to reproduce:
As far as I can tell, the user is doing these steps to reproduce:
1. Open Journey Maps to the fullscreen map
2. Scroll around looking at different sections of the map

#### Additional Information:
- Crash Report: https://pastebin.com/eyZna50W
____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

-Minecraft: 1.12.2
-Forge: 14.23.2.2641
-Pack: All the Mods 3 5.9.2
-Biomes O' Plenty: 7.0.1.2334
-Journey Maps: 5.5.2

**Comment by Forstride** [comment] 2018-04-10 23:26
It is pretty much the same as #1029, but I'll leave it open since the JourneyMap info might help, especially since they can reproduce it.

**Comment by Forstride** [comment] 2019-05-25 07:14
Closing this because we either can't/won't fix it or it's not an issue in 1.13

**Closed by Forstride** 2019-05-25 07:14 UTC
Labels: bug-major
