### ISSUE TITLE
Hot Spring Water makes you basically a god

### ISSUE THREAD

**Issue by DoragonKeiyou** [Glitchfiend/BiomesOPlenty#1178] opened 2018-02-09 04:26 UTC
#### Issue Description:

Hot Spring Water makes you basically unkillable.  It instantly heals you to full rather than just applying a regeneration effect.  I remember it back in much MUCH older versions only applying the regen.  If this is an intended feature, is there maybe a config we can get for it to not heal you for 50HP/sec?  I'm fine with it just giving regeneration, but standing in it to cheese any boss fight feels almost like playing on creative.  (I understand "just don't stand in it" but it's more from a multiplayer standpoint)

#### Steps to reproduce:

1.  Find hot spring water.
2.  Stand in it.
3.  Be healed faster than taking any amount of damage that doesn't automatically kill you.

#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 7.0.1 (7.0.1.2313)
- Minecraft: 1.12.2
- Forge: 14.23.2.2611

**Comment by DoragonKeiyou** [comment] 2018-03-04 21:15
If it's in fact how MC itself handles Regeneration, then maybe having it check for entity collision every 40-50 ticks instead of every tick would fix the issue entirely, more similarly to how the beacons operate.  I would go further to suggest maybe having the tick rate at which it checks be a configuration option for those who wouldn't want the "nerf".

**Comment by Khioni** [comment] 2019-03-27 16:04
Same type of glitch seems to affect Liquid Poison, which when combined with NoDamI (confirmed with NoDamI 1.12.2-1.2), makes it a near-instant HP to 1, but without that mod would make you take damage every half-second instead of the usual poison timing.

**Comment by Forstride** [comment] 2019-05-25 07:15
Closing this because we either can't/won't fix it or it's not an issue in 1.13

**Closed by Forstride** 2019-05-25 07:15 UTC
Labels: enhancement
