### ISSUE TITLE
Climate lookup failed

### ISSUE THREAD

**Issue by Renari** [Glitchfiend/BiomesOPlenty#1363] opened 2019-03-19 19:07 UTC
#### Issue Description:
I was not able to reproduce this crash, but I figured it is worth reporting anyway.

#### Steps to reproduce:

1. Exit end portal.

#### Additional Information:

http://openeye.openmods.info/crashes/e251f4ab9c3a91388299edc7c1e6a905

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 7.0.1
- Minecraft: 1.12.2
- Forge: 14.23.5.2815
- Recurrent Complex; 1.4.7

**Comment by Renari** [comment] 2019-03-19 19:08
https://github.com/Ivorforce/RecurrentComplex/issues/380

**Comment by matthieu1345** [comment] 2019-03-29 13:02
https://pastebin.com/iXp8SFgP

i've had the same happen to my server.
happened once, not been able to reproduce so far

same bop, mc, and forge versions

**Comment by Forstride** [comment] 2019-05-25 07:24
Closing this because we either can't/won't fix it or it's not an issue in 1.13

**Closed by Forstride** 2019-05-25 07:24 UTC
