### ISSUE TITLE
On wiki, Blocks, Items, and Mobs links redirect to homepage

### ISSUE THREAD

**Issue by Daeruin** [Glitchfiend/BiomesOPlenty#1177] opened 2018-02-07 04:38 UTC
When I click on the links for Blocks, Items, or Mobs on the right-hand sidebar of the GitHub wiki, it redirects me to the homepage.

**Comment by Adubbz** [comment] 2018-02-07 04:53
Duplicate of https://github.com/Glitchfiend/BiomesOPlenty/issues/1148

**Closed by Adubbz** 2018-02-07 04:53 UTC
