### ISSUE TITLE
[1.8] crash during world load

### ISSUE THREAD

**Issue by croftyraider** [Glitchfiend/BiomesOPlenty#535] opened 2015-09-13 20:37 UTC
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.59-176.jar)
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  BetterFps (BetterFps-1.1.0.jar)
  BOPLoadingPlugin (BiomesOPlenty-1.8-3.0.0.1389-universal.jar)
  CoreMod (Aroma1997Core-1.8-1.0.3.4.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 9/13/15 10:27 AM
Description: Exception preparing structure feature

java.lang.ArrayIndexOutOfBoundsException: 117
	at biomesoplenty.common.world.layer.GenLayerClimate.func_75904_a(GenLayerClimate.java:30)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:19)
	at biomesoplenty.common.world.layer.GenLayerBiomeIslands.func_75904_a(GenLayerBiomeIslands.java:33)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:19)
	at biomesoplenty.common.world.layer.GenLayerBiomeEdgeBOP.func_75904_a(GenLayerBiomeEdgeBOP.java:30)
	at biomesoplenty.common.world.layer.GenLayerSubBiomesBOP.func_75904_a(GenLayerSubBiomesBOP.java:31)
	at biomesoplenty.common.world.layer.GenLayerBiomeIslands.func_75904_a(GenLayerBiomeIslands.java:32)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:19)
	at biomesoplenty.common.world.layer.GenLayerRaggedEdges.func_75904_a(GenLayerRaggedEdges.java:27)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:19)
	at net.minecraft.world.gen.layer.GenLayerShore.func_75904_a(SourceFile:15)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:19)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:19)
	at net.minecraft.world.gen.layer.GenLayerSmooth.func_75904_a(SourceFile:15)
	at biomesoplenty.common.world.layer.GenLayerRiverMixBOP.func_75904_a(GenLayerRiverMixBOP.java:39)
	at net.minecraft.world.biome.WorldChunkManager.func_76940_a(WorldChunkManager.java:191)
	at net.minecraft.world.gen.structure.MapGenVillage.func_75047_a(SourceFile:67)
	at net.minecraft.world.gen.structure.MapGenStructure.func_180701_a(MapGenStructure.java:38)
	at net.minecraft.world.gen.MapGenBase.func_175792_a(SourceFile:28)
	at biomesoplenty.common.world.ChunkProviderGenerateBOP.func_180514_a(ChunkProviderGenerateBOP.java:654)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
	at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:164)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at biomesoplenty.common.world.layer.GenLayerClimate.func_75904_a(GenLayerClimate.java:30)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:19)
	at biomesoplenty.common.world.layer.GenLayerBiomeIslands.func_75904_a(GenLayerBiomeIslands.java:33)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:19)
	at biomesoplenty.common.world.layer.GenLayerBiomeEdgeBOP.func_75904_a(GenLayerBiomeEdgeBOP.java:30)
	at biomesoplenty.common.world.layer.GenLayerSubBiomesBOP.func_75904_a(GenLayerSubBiomesBOP.java:31)
	at biomesoplenty.common.world.layer.GenLayerBiomeIslands.func_75904_a(GenLayerBiomeIslands.java:32)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:19)
	at biomesoplenty.common.world.layer.GenLayerRaggedEdges.func_75904_a(GenLayerRaggedEdges.java:27)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:19)
	at net.minecraft.world.gen.layer.GenLayerShore.func_75904_a(SourceFile:15)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:19)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:19)
	at net.minecraft.world.gen.layer.GenLayerSmooth.func_75904_a(SourceFile:15)
	at biomesoplenty.common.world.layer.GenLayerRiverMixBOP.func_75904_a(GenLayerRiverMixBOP.java:39)
	at net.minecraft.world.biome.WorldChunkManager.func_76940_a(WorldChunkManager.java:191)
	at net.minecraft.world.gen.structure.MapGenVillage.func_75047_a(SourceFile:67)

-- Feature being prepared --
Details:
	Is feature chunk: False
	Chunk location: 4,-47
	Chunk pos hash: -201863462908
	Structure type: net.minecraft.world.gen.structure.MapGenVillage
Stacktrace:
	at net.minecraft.world.gen.structure.MapGenStructure.func_180701_a(MapGenStructure.java:38)
	at net.minecraft.world.gen.MapGenBase.func_175792_a(SourceFile:28)
	at biomesoplenty.common.world.ChunkProviderGenerateBOP.func_180514_a(ChunkProviderGenerateBOP.java:654)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
	at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:164)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Mac OS X (x86_64) version 10.10.5
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2613929280 bytes (2492 MB) / 3113877504 bytes (2969 MB) up to 3113877504 bytes (2969 MB)
	JVM Flags: 5 total; -XX:+UseParNewGC -XX:+AggressiveOpts -XX:+TieredCompilation -Xms3G -Xmx3G
	IntCache: cache: 0, tcache: 67, allocated: 0, tallocated: 21
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1513 27 mods loaded, 27 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1513.jar) 
	UCHIJAAAA	Forge{11.14.3.1513} [Minecraft Forge] (forge-1.8-11.14.3.1513.jar) 
	UCHIJAAAA	Aroma1997Core{1.0.3.4} [Aroma1997Core] (Aroma1997Core-1.8-1.0.3.4.jar) 
	UCHIJAAAA	betterfps{1.1.0} [BetterFps] (minecraft.jar) 
	UCHIJAAAA	bspkrsCore{7.01} [bspkrsCore] ([1.8]bspkrsCore-universal-7.01.jar) 
	UCHIJAAAA	Treecapitator{1.8} [Treecapitator] ([1.8]Treecapitator-universal-2.0.5.jar) 
	UCHIJAAAA	Aroma1997CoreHelper{1.0.3.4} [Aroma1997Core|Helper] (Aroma1997Core-1.8-1.0.3.4.jar) 
	UCHIJAAAA	Aroma1997sDimension{1.0} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.8-1.1.1.0.jar) 
	UCHIJAAAA	basemetals{1.4.0} [Base Metals] (BaseMetals-1.4.0.jar) 
	UCHIJAAAA	BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8-3.0.0.1389-universal.jar) 
	UCHIJAAAA	Chameleon{1.8-0.1.0} [Chameleon] (Chameleon-1.8-0.1.0.jar) 
	UCHIJAAAA	decorationmegapack{1.18} [Decoration Mega Pack] (decorationmegapack-1.18-1.8-1446.jar) 
	UCHIJAAAA	expchest{4.0} [Exp Chest] (expchest-4.0.jar) 
	UCHIJAAAA	inventorytweaks{1.59-176-9318a76-dirty} [Inventory Tweaks] (InventoryTweaks-1.59-176.jar) 
	UCHIJAAAA	IronChest{6.0.107.754} [Iron Chest] (ironchest-1.8-6.0.107.754-universal.jar) 
	UCHIJAAAA	fyberbackpack{1.0} [Just Backpacks] (justbackpacks-mc1.8-1.0.jar) 
	UCHIJAAAA	llor{1.0.2} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.0.2-mc1.8.0.jar) 
	UCHIJAAAA	plantmegapack{5.08} [Plant Mega Pack] (plantmegapack-5.08-1.8-1450.jar) 
	UCHIJAAAA	poweradvantage{1.2.4} [Power Advantage] (PowerAdvantage-1.2.4.jar) 
	UCHIJAAAA	projectbench{0.5.0} [Project Bench Updated] (ProjectBench-Update-1.8-0.5.0.jar) 
	UCHIJAAAA	AS_Ruins{15.2} [Ruins Spawning System] (Ruins-1.8.jar) 
	UCHIJAAAA	shipwrecks{1.7.0} [Shipwrecks!] (shipwrecks-1.8.0-1.7.1.jar) 
	UCHIJAAAA	steamadvantage{1.3.3} [Steam Advantage] (SteamAdvantage-1.3.3.jar) 
	UCHIJAAAA	StorageDrawers{1.8-2.1.6} [Storage Drawers] (StorageDrawers-1.8-2.1.6.jar) 
	UCHIJAAAA	reinforcedmod{Updated for 1.8} [Reinforced Mod] (The Reinforced Mod 1.8(v1.4.0).jar) 
	UCHIJAAAA	AS_UpdateCheck{1.1.7} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.8.jar) 
	Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.59-176.jar)
  invtweaks.forge.asm.ContainerTransformer
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
BetterFps (BetterFps-1.1.0.jar)
  me.guichaguri.betterfps.BetterFpsTransformer
BOPLoadingPlugin (BiomesOPlenty-1.8-3.0.0.1389-universal.jar)
  
CoreMod (Aroma1997Core-1.8-1.0.3.4.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['croftyraider'/328, l='w7', x=25.11, y=64.00, z=-864.63]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by croftyraider** [comment] 2015-09-13 23:40
FYI - This happened during the period when the minecraft login/session servers were having trouble today, so unwittingly I was trying to play "offline". Since the servers have come back up, the crash on load has stopped happening.

**Comment by Adubbz** [comment] 2016-01-06 13:15
I have seen this happen once or twice although i'm struggling to reproduce it consistently with BoP on its own. If there's a specific seed/coordinate you know of where this always happens that'd be very helpful

**Comment by Adubbz** [comment] 2016-01-12 08:39
I'm going to close this for the time being as I can't seem to reproduce it again. *However*, I have added debug code to build 1627 should this occur again. If a similar issue happen on that version or greater, feel free to open another issue and make sure to include full logs, not just the crash report.

**Closed by Adubbz** 2016-01-12 08:39 UTC
Labels: 1.8.9

**Comment by Adubbz** [comment] 2016-01-12 09:42
This should hopefully be fixed now, turns out it was a rounding error which occurred very rarely

**Comment by croftyraider** [comment] 2016-01-12 17:09
Thanks :) I was thinking, trying to come up with a way to repeat it, but when I had seen it while I was playing modded 1.8, it was extremely rare, so I wasn't getting anywhere. Glad you found it!
