### ISSUE TITLE
[1.11.2] Chunk Islands [Bug]

### ISSUE THREAD

**Issue by Quizer9O8** [Glitchfiend/BiomesOPlenty#991] opened 2017-04-24 07:42 UTC
#### Issue Description:
Strange Chunk Islands are appearing in the world.

#### Steps to reproduce:
0. Make sure you've installed 'Geographicraft/Climate Control'
1.  Go to 'Create new world'
2. Go to 'More world options' and Select 'Biomes O' Plenty'
3. Click on 'Customize'
4. Change 'Biome Size' to 'HUGE', 'Temperature' to 'LARGE_ZONES', 'Landmass' to 'CONTINENTS' and 'Rainfall' to 'LARGE_ZONES'
5. Give the seed this name: Biomes O' Plenty
6. Go to the coordinates X: 383 and Z: 463

#### Additional Information:

- Screenshots:
![2017-04-24_09 27 58](https://cloud.githubusercontent.com/assets/19509275/25326714/b078ae90-28d1-11e7-9db5-3a132cb3cc81.png)
____
#### Affected Versions

- Biomes O' Plenty: 1.11.2-6.1.0.2193
- Minecraft: 1.11.2
- Forge: 13.20.0.2261

**Comment by Adubbz** [comment] 2017-04-25 12:58
I'm a bit confused as to why you'd be using climate control along with the BoP worldtype. Isn't it mainly for use with worldtypes that don't normally support our biomes (e.g. RTG)?

**Comment by Quizer9O8** [comment] 2017-04-30 09:13
No it can also be used for BOP or any other biome adding mod

**Comment by Syndaryl** [comment] 2017-04-30 14:10
It's useful for e.g. putting JungleCraft biomes in BoP worldtypes. The base concept is "take world generation specific biomes from one mod to another type of world generation".

**Comment by Forstride** [comment] 2018-03-02 01:37
Closing this, because no offense, but you seem to be the only person who has these chunk issues, and no one else can reproduce them.

**Closed by Forstride** 2018-03-02 01:37 UTC
