### ISSUE TITLE
1.10.2 Crash on Load - BiomesOPlenty-1.10.2-5.0.0.2078-universal

### ISSUE THREAD

**Issue by MokahTGS** [Glitchfiend/BiomesOPlenty#850] opened 2016-08-26 02:04 UTC
Forge 2072
BiomesOPlenty-1.10.2-5.0.0.2078-universal

http://pastebin.com/ag7Dxfys

**Comment by Forstride** [comment] 2016-08-26 03:16
It seems to be caused by Terrain Crystals Addons.  They need to update it to use the new location of BOPWoods (Which is in our actual API now...Not sure why it wasn't before)

**Comment by DrasticDemise** [comment] 2016-08-29 00:02
This is fixed in the latest version that I am about to push

**Closed** 2016-08-29 00:03 UTC
