### ISSUE TITLE
[1.12.2] Settings for World Creation

### ISSUE THREAD

**Issue by NickelHub** [Glitchfiend/BiomesOPlenty#1272] opened 2018-06-06 20:00 UTC
Before creating a world the second setting page is completly empty. Where are the options gone, e.g. lake density?

**Comment by Maxiride** [comment] 2018-06-09 13:40
It is mentioned in #623 that it will be implemented and it is currently a placeholder.

Yet the wiki is lacking any information about the currently available settings, I'm trying to figure them out by trial and error and some googling but the Github wiki should definitively be updated with them even if all the pages aren't completed yet.

**Comment by Sanofus** [comment] 2018-06-09 15:32
I try to create a world with less lakes because I think there are to much. If JourneyMap is installed you can a landscape looking like a cheese.

**Comment by whitestarx0312** [comment] 2018-06-17 17:36
Does anyone know where the world settings are stored? I'm wanting to use them on a server but I'm unsure how to do that. I feel like if I start the world on my local computer with the settings and upload it to the server that might work, if the settings are being stored and respected somewhere within the world's files.

**Comment by srs-bsns** [comment] 2018-06-20 14:06
You should be able to put the settings into the file `config/biomesoplenty/world.json` and they will be loaded when you start Minecraft. The file doesn't exist by default, so you will have to create it yourself.

The format is identical to the string you would use in `generator-settings` in the `server.properties` file for a dedicated server.

Example:
```json
{
    "landScheme":"vanilla",
    "tempScheme":"medium_zones",
    "rainScheme":"medium_zones",
    "biomeSize":"medium",
    "amplitude":1.0,
    "generateBopOre":true,
    "generatePoisonIvy":true,
    "generateFlax":true,
    "generateBerryBushes":true,
    "generateThorns":true,
    "generateQuicksand":true,
    "generateLiquidPoison":true,
    "generateHotSprings":true,
    "generateNetherHives":true,
    "generateEndFeatures":true
}
```

**Comment by Sanofus** [comment] 2018-06-20 17:18
That are not the settings I am looking for. I seek the settings for lake density like for the custom world type of vanilla minecraft. If that does not exist that should be created as request for adding this.

**Comment by srs-bsns** [comment] 2018-06-20 19:38
I only gave you an example of the settings that are unique to BoP. Most of the vanilla settings should still exist and can be added to the `world.json` file in the same manner.

You want to use `waterLakeChance`, which works in the BIOMESOP world type according to: https://github.com/Glitchfiend/BiomesOPlenty/blob/5c092bd853489f3509191568ebb46b8656b5c059/src/main/java/biomesoplenty/common/world/ChunkGeneratorOverworldBOP.java#L536-L541

**Comment by Sanofus** [comment] 2018-06-21 11:38
@srs-bsns That only shows the BOP source code. That did not explain what I have to add to the world.json.

@Maxride No, to change only one setting that is available in vanilla no mod should be required.

**Comment by Sanofus** [comment] 2018-06-21 11:41
I will try to add "waterLakeChance":60 to world.json.

**Comment by srs-bsns** [comment] 2018-06-21 12:53
>That only shows the BOP source code. That did not explain what I have to add to the world.json.

Sorry, I thought I made it clear in my last message. All you need to do is add the vanilla setting to the `world.json` file and it should work. I only referenced the source to show that it actually used the setting.

This is all you need:
```json
{
    "waterLakeChance":60
}
```

**Comment by Sanofus** [comment] 2018-06-21 12:59
Does this have to be in a separate section? I added:

"waterLakeChance":70,
"seaLevel":2 // just to test if setting is respected
to the world.json. 
Both of them weren't respected as the world was created. 
https://pastebin.com/05QUpzTb

**Comment by Sanofus** [comment] 2018-06-22 15:59
@srs-bsns It seems that the world.json is not able to change vanilla settings but if you add the same to the server.properties it will be applied. Is that a bug or hasn't this been a feature?

**Comment by srs-bsns** [comment] 2018-06-22 20:36
The settings in `server.properties` are applied differently on a dedicated server and it is obviously no help on the client for single-player.
Everything is in place to load settings from the `world.json` file, so I'm not sure why it's not working. I am not a developer of BoP, so you will have to ask them.

**Comment by Sanofus** [comment] 2018-06-22 20:48
@Maxiride Unfortunately OTG is compatible with BOP. It shows a warning if BOP is installed.

@Forstride could tell us more maybe?

**Comment by Axieum** [comment] 2018-06-24 22:42
Unfortunately, by looking at the code, only the height and noise variations are configurable alongside the BOP options in said `world.json` file.

I'm not sure why they didn't just add the extra few lines to set the other vanilla options.

https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.12.x-7.0.x/src/main/java/biomesoplenty/common/world/BOPWorldSettings.java

**Comment by Sanofus** [comment] 2018-06-25 07:03
> // Vanilla properties - not configurable (yet) but included for consistency with vanilla ChunkProviderSettings
This seems to be the responsible line. I will look into the code again but I assume that it has technically reason that there are not a few lines more. Maybe the game prevents changing its values if the world type is not set to CUSTOM. But it might also be that it is just a forgotten task.

**Comment by TheSnowyChickens** [comment] 2018-08-14 16:27
BoP NEED a good config by Default, this 3 options atm is not enough.

**Comment by codydbgt** [comment] 2019-05-04 19:23
i need sealevel for my modpack :/

**Comment by Forstride** [comment] 2019-05-25 07:17
Duplicate of #623

**Closed by Forstride** 2019-05-25 07:17 UTC
