### ISSUE TITLE
No proper block texture for flowering oak leaves

### ISSUE THREAD

**Issue by Goht** [Glitchfiend/BiomesOPlenty#1105] opened 2017-09-14 22:32 UTC
Flowering oak leaves have a texture in the inventory, but are placed or grown with no texture , the pink and black squares. The inverse is true for certain mushrooms, but I don't recall which.

**Comment by Adubbz** [comment] 2017-09-25 00:52
Duplicate of https://github.com/Glitchfiend/BiomesOPlenty/issues/1061

**Closed by Adubbz** 2017-09-25 00:52 UTC
