### ISSUE TITLE
Grass, cattails, lilly pads randomly pop out of the ground like they have been destroyed

### ISSUE THREAD

**Issue by cquick7** [Glitchfiend/BiomesOPlenty#1320] opened 2018-10-06 21:15 UTC
#### Issue Description:

Grass, cattails, and, lilly pads,
 some flowers will randomly pop out of the ground as an item.  The grass will disappear and a seed will appear in its place.  Basically, these items act as they have been broken by hand.  It occurs on our server world, usually when traveling and reloading new terrain, but it can happen without traveling too.  Occurs most in swamp biomes.

#### Steps to reproduce:

1. Just start traveling, 90% of the time it happens in a swamp.
2. 
3. 

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log:
- Screenshots: ![2018-10-06_15 12 36](https://user-images.githubusercontent.com/43917061/46575831-71f6e880-c97a-11e8-9ddd-71ddb8d0b82a.png)

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: BiomesOPlenty-1.12.2-7.0.1.2399
- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.4.2705

**Comment by Graywaren** [comment] 2019-02-09 23:09
Yea, I see this a lot with plenty of different objects as well. My guess is that it has to do with lighting levels or other requirements the plant needs not being met when it actually generates/changes from another mod, so I've just been ignoring it. Would like to know if that actually is the cause or if its a bug.

**Comment by Forstride** [comment] 2019-05-25 07:23
Closing this because we either can't/won't fix it or it's not an issue in 1.13

**Closed by Forstride** 2019-05-25 07:23 UTC
