### ISSUE TITLE
[1.16.3] Unable to log in to a multiplayer server - Received invalid biome id: -1

### ISSUE THREAD

**Issue by ProsperCraft** [Glitchfiend/BiomesOPlenty#1681] opened 2020-09-30 02:25 UTC
### What's the issue you encountered?

I set up a dedicated server with only BOP on the server and client, when you try to connect with the client you get thousands of lines of log spam of - Received invalid biome id: -1  the client locks up and is unresponsive until you kill the server.

No other mods were installed on the client or server, NO OPTIFINE, I know better.

### Logs
Client log-
https://gist.github.com/ProsperCraft/a904ad71638c3a51b211f0fd4a82c79a

### Mod Version
BiomesOPlenty-1.16.3-12.0.0.400-universal

**Comment by ProsperCraft** [comment] 2020-09-30 03:59
If you leave your client for a really long time, you eventually get fully logged in and can move a little and the client locks up again while the logs spams several hundred times a second.

**Comment by N3ROO** [comment] 2020-10-03 13:12
Same issue here when trying to generate a world (singleplayer). The mod does not work for 1.16.3 for some reason (forge 34.1.0).

**Comment by NielsjeNL** [comment] 2020-10-05 18:40
Hitting the same issue. With BoP loaded my MultiMC log is just being spammed as follows:
```[m[33m[20:27:17] [Render thread/WARN] [minecraft/BiomeContainer]: Received invalid biome id: -1
[m[33m[20:27:17] [Render thread/WARN] [minecraft/BiomeContainer]: Received invalid biome id: -1
[m[33m[20:27:17] [Render thread/WARN] [minecraft/BiomeContainer]: Received invalid biome id: -1
[m[33m[20:27:17] [Render thread/WARN] [minecraft/BiomeContainer]: Received invalid biome id: -1
[m[33m[20:27:17] [Render thread/WARN] [minecraft/BiomeContainer]: Received invalid biome id: -1
[m[33m[20:27:17] [Render thread/WARN] [minecraft/BiomeContainer]: Received invalid biome id: -1
[m[33m[20:27:17] [Render thread/WARN] [minecraft/BiomeContainer]: Received invalid biome id: -1
[m[33m[20:27:17] [Render thread/WARN] [minecraft/BiomeContainer]: Received invalid biome id: -1
[m[33m[20:27:17] [Render thread/WARN] [minecraft/BiomeContainer]: Received invalid biome id: -1
[m[33m[20:27:17] [Render thread/WARN] [minecraft/BiomeContainer]: Received invalid biome id: -1
[m[33m[20:27:17] [Render thread/WARN] [minecraft/BiomeContainer]: Received invalid biome id: -1
MultiMC stopped watching the game log because the log length surpassed 100000 lines.
You may have to fix your mods because the game is still logging to files and likely wasting harddrive space at an alarming rate!
```

When I do get in, the game is unplayable due to extreme lag (full-on freezes taking 3+ seconds). Disabling BoP but no other mods fixes the issue. This is using `BiomesOPlenty-1.16.3-12.0.0.403-universal.jar`, Forge version 34.1.0.

**Comment by BrentonVI** [comment] 2020-10-10 07:12
I can confirm that this exact issue is continuing to happen with `BiomesOPlenty-1.16.3-12.0.0.405-universal.jar` and Forge version 34.1.10, rendering multiplayer all but unplayable while singleplayer is seemingly unaffected.

**Comment by Forstride** [comment] 2020-10-12 18:15
Try on the latest version now.  Various server-related issues were fixed, so it's possible this was included in that

**Comment by Adubbz** [comment] 2020-11-09 00:47
Closing this as presumably it's no longer an issue.

**Closed by Adubbz** 2020-11-09 00:47 UTC
Labels: bug-minor
