### ISSUE TITLE
bug with betterend

### ISSUE THREAD

**Issue by Celophy** [Glitchfiend/BiomesOPlenty#1775] opened 2020-12-30 11:32 UTC
## Bug Report

 the mod betterend dont generate the biomes in the end, when BOP is installed

### How can the issue be reproduced?

install the betterend forge and biomes o plenty

### Mod Version
the lastest

**Comment by Adubbz** [comment] 2020-12-30 11:34
Duplicate of #1755

**Closed by Adubbz** 2020-12-30 11:34 UTC
Labels: bug-minor
