### ISSUE TITLE
 BOP creative tab selection crash

### ISSUE THREAD

**Issue by Spr18JSyiFMR** [Glitchfiend/BiomesOPlenty#1251] opened 2018-04-25 00:40 UTC
#### Issue Description:

I have limited knowledge of programming and correct me if I'm wrong but basically what is happening here is when I am in creative mode and the BOP tab is clicked, the program can't find something related to this tab that is needed to display the tab's content.

I've narrowed it down to a conflict with the following mods in my folder:

  - ImmersiveEngineering-0.12-81
    - Possibly (because they are dependent on the above so I can't test them):
       - alternatingflux-0.12-4
       - ImmersiveCables-1.12.2-1.3.0
       - ImmersiveRailroading-1.0.1_1.12
       - immersivetech-1.12-1.3.7-SevTech-Ages
       - IndustrialWires-1.6-25

 - bc-ore-processing-7.99.15-1

 - binnie-mods-1.12.2-2.5.0.163

 - TConstruct-1.12.2-2.9.1.65
     - Possibly (because they are dependent on the above so I can't test them):
       - moartinkers-0.5.4

This may or may not be related to the error too:
  After the closing of the server (saving of the world data, etc...) and launcher displaying the crash report, any attempt to load the crashed world will result in the world successfully loaded and terrain and all, but the game will either slow to a crawl then not respond or straight up not respond (note: the game must be unpaused for this processes to start). -- Note: this might just be a memory related issue on my side.

#### Steps to reproduce:
1. have one or more of the mods listed above installed along with BOP 
2. open up an existing or create a new world
3. be in creative mode
4. navigate to the BOP tab and click it
5. game will stall then crash

#### Additional Information:
[crash-2018-04-24_20.26.04-client.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/1945056/crash-2018-04-24_20.26.04-client.txt)

- fml-client-latest.log or fml-server-latest.log: [https://pastebin.com/bAbcknDj](url)

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: BiomesOPlenty-1.12.2-7.0.1.2381-universal
- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.3.2673

**Comment by GirafiStudios** [comment] 2018-04-25 00:44
Fixed in 7.0.1.2382. Duplicate of https://github.com/Glitchfiend/BiomesOPlenty/issues/1250

**Closed** 2018-04-26 07:53 UTC

**Comment by Axelandre42** [comment] 2018-11-02 12:06
Issue is back in 7.0.1.2402
[crash-2018-10-31_12.15.59-client.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/2542351/crash-2018-10-31_12.15.59-client.txt)
