### ISSUE TITLE
[1.11.2] NetherEx and BOP compatibility

### ISSUE THREAD

**Issue by LogicTechCorp** [Glitchfiend/BiomesOPlenty#988] opened 2017-04-22 03:27 UTC
#### Issue Description:
I am developing a mod that adds in biomes to the Nether. I am currently working on support for BOP's Nether biomes. I have BOP's Nether biomes spawning alongside my own, but I have come across the issue that BOP's Nether biomes do not generate resources unless the world type is set to Biomes O' Plenty. Is there some workaround the can be implemented to resolve this?

#### Affected Versions
- Biomes O' Plenty: 6.0.2.2190
- NetherEx: Unreleased/Dev
- Minecraft: 1.11.2
- Forge: 13.20.0.2282

**Comment by Forstride** [comment] 2017-04-22 14:25
People are supposed to be using the BOP world type when they use BOP...I don't see what the issue is...

**Comment by Adubbz** [comment] 2017-04-23 01:26
I think the confusion comes from a different bug where BoP's Nether biomes appear in world types that they shouldn't. This comes as a result of having to override Vanilla's WorldProvider for the Nether, and there's not really a good way of doing that selectively based on the world type.

So this is _sort of_ intended behaviour.

**Comment by Sanofus** [comment] 2018-05-31 17:22
You can add a script to NetherEx which let its biomes spawn with BOP biomes for the nether. Look on their site.

**Comment by Forstride** [comment] 2019-05-25 07:13
Closing this because we either can't/won't fix it or it's not an issue in 1.13

**Closed by Forstride** 2019-05-25 07:13 UTC
Labels: compatibility
