### ISSUE TITLE
BOP + Terralith = Wasteland Still Bugged spawning grass instead of salt

### ISSUE THREAD

**Issue by zachsai** [Glitchfiend/BiomesOPlenty#2010] opened 2022-06-06 04:39 UTC
### What's the issue you encountered?

![2022-06-06_00 37 40](https://user-images.githubusercontent.com/63996164/172095854-bb80ada3-1584-4358-a1b9-25d304733661.png)
you can see here what it looks like. when both mods are installed, wasteland is bugged for an odd reason

### How can the issue be reproduced?

BOP + Terralith + tp to wasteland

### Mod Version

16.0.0.115

**Comment by Adubbz** [comment] 2022-06-11 01:34
Duplicate of #1996

**Closed as completed by Adubbz** 2022-06-11 01:34 UTC
Labels: bug

**Comment by zachsai** [comment] 2022-06-12 00:51
Which update has this fixed? The latest patch from 13 hours ago does not seem to have it fixed :)

**Comment by Adubbz** [comment] 2022-06-12 00:52
This was a TerraBlender issue, not BOP. It has been fixed in that accordingly

**Comment by zachsai** [comment] 2022-06-12 01:02
Is that version of terrablender up for 1.18.2?
If so, what is the version called? :)

**Comment by Answordy** [comment] 2022-07-07 04:24
> Is that version of terrablender up for 1.18.2? If so, what is the version called? :)

No there is no 1.18.2 version with a fix, sadly 1.18.2 is not supported anymore, not even for maintenance. You can use TerraBlender 1.1.0.98, as it's the last version without this issue, however, using that, other, already fixed problems might comeback. Using 1.19 is also an option, though that may require bigger sacrifices, considering the lack of mods, a stable forge version, and a bunch of other problems.

**Comment by puppygruel** [comment] 2022-09-04 01:24
> Is that version of terrablender up for 1.18.2? If so, what is the version called? :)

terrablender released a beta version for 1.18.2 that fixes the issue, the file is TerraBlender-forge-1.18.2-1.2.0.126
