### ISSUE TITLE
Mod-Added Wood Blocks Should Count For "Getting Wood" Achievement

### ISSUE THREAD

**Issue by airbreather** [Glitchfiend/BiomesOPlenty#502] opened 2015-07-02 16:34 UTC
Software Configuration used for testing
--
- Forge 10.13.4.1448-1.7.10
- BiomesOPlenty-1.7.10-2.1.0.1364-universal.jar (MD5: 7aa072f0f943d67d5dbf7ad1a259b673)

I've also confirmed this to still be present in the current latest public builds of Forge and BoP for 1.8, though I only have detailed steps for 1.7.10:
- Forge 11.14.3.1487-1.8
- BiomesOPlenty-1.8-3.0.0.1365-universal.jar (MD5: e74ad3aa360540affbc3dd2ed352e234)

Repro steps
--
1. Optional: in forge.cfg, set B:spawnHasFuzz=false and I:defaultSpawnFuzz=0 to see exactly what I saw right away.
2. Start Minecraft.
3. Create a new world, with World Type: Biomes O' Plenty, Seed: -8030104888094733544.  Leave other options at their defaults.
4. Whenever you spawn into the world, open your inventory to get the "Taking Inventory" achievement.
5. Head to x=34, y=67, z=1003, which is a location right next to a tree.
6. Harvest one or more blocks of Pine Wood from this tree:
![Step 6 Screenshot](https://cloud.githubusercontent.com/assets/3792815/8481797/570565c4-20b3-11e5-80da-53bc6a02eab9.png)
7. Now head to x=27, y=68, z=975, which is a location right next to another tree.
8. Harvest one or more blocks of Spruce Wood from this tree.
![Step 8 Screenshot](https://cloud.githubusercontent.com/assets/3792815/8481796/57022936-20b3-11e5-815f-cb52da099531.png)

Expected: the "Getting Wood" achievement should have been completed on step 6.
Actual: the "Getting Wood" achievement is only completed at step 8.

Impact
--
On some mod packs, players can find themselves starting off in very hazardous locations, and achievements are not immediately on their minds as much as survival.  The vanilla Minecraft achievement system is set up so that the natural first-steps into the world reward some "starter" achievements; if the player happens to spawn into a biome that has BoP-added trees and miss "Getting Wood", they will find themselves behind the curve, having to play "catch-up" sometime later once they find some vanilla wood blocks if they want to get nearly any vanilla achievements at all.

It's obviously not the end of the world the way it is right now, but I couldn't find something like this in the GitHub issue tracker or the code no matter how hard I searched (I didn't look through every commit since 1.7.10, though I did at least do a surface-level confirmation that it's still a thing in 1.8, as mentioned above).  I'm not familiar with what you get from the Forge API as far as possible ways of fixing this, so I'm not 100% sure this is something you guys can reasonably fix.  If nothing else, I'd at least like to be able to point to either an "open" or a "wontfix" issue on GitHub if someone asks about this.

**Comment by Syndaryl** [comment] 2015-07-02 16:54
I can confirm I'm seeing this issue. I've been seeing it for a while and never quite got around to reporting it, so thank you for the good bug report I can put a confirmation on :)

**Comment by Adubbz** [comment] 2015-07-02 23:49
Wow... I have to commend you for providing such a detailed outline of the issue. It's not very often I would see someone putting effort into their issue reports - for that, I thank you :)

Achievements are something that has been added by the mod in the past, but aside from certain usage by some modpacks/map makers, they are mostly useless. They're probably not something i'd revisit 1.7 for, although they should most certainly be handled at some point for 1.8. I'll add this to the list of things to do for the first 1.8 release. We probably won't add our own custom achievements until later on, however this should be reasonable enough to do.

**Comment by airbreather** [comment] 2015-07-04 00:40
Just discovered partially by accident that MFR Rubber Wood does this.  [Here's](https://github.com/skyboy/MineFactoryReloaded/commit/1de6352d7520961d2b5a69a4c57096459856f44c) the commit made it happen; looks fairly straightforward.

**Comment by Adubbz** [comment] 2015-07-07 06:00
The latest version for 1.7 should now support this since I just merged a pull request from @fewizz  adding this functionality. I'll leave this open as a reminder to add it for 1.8 as well

**Closed** 2015-12-16 01:15 UTC
Labels: 1.8, enhancement
