### ISSUE TITLE
Editing noticeboards can cause the game to crash

### ISSUE THREAD

**Issue by SadEPa28** [Glitchfiend/BiomesOPlenty#2203] opened 2024-04-11 15:01 UTC
### What's the issue you encountered?

If you edit any of the notice boards in the mod, it willlllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll
![willlllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll](https://github.com/Glitchfiend/BiomesOPlenty/assets/159880091/2f32800c-50e4-496f-8658-b556af3afe1b)

### How can the issue be reproduced?

edit any of the notice boards in the mod.

### Logs

N/A

### Mod Version

19.0.0.79

### Additional information

The text is translated from Chinese and may contain errors.

**Comment by Forstride** [comment] 2024-04-11 17:37
I can't replicate this with only Biomes O' Plenty, and we can't do anything more without an actual crash report/log.

**Comment by SadEPa28** [comment] 2024-04-12 04:25
I'll try to get the game to crash out and generate an error report instead of staying unresponsive. And just then, when I clicked on the translate button, Microsoft Edge was unresponsive and crashed :)

**Comment by Forstride** [comment] 2024-05-05 01:00
Closing since no additional information was provided, and it's unlikely this was caused by BOP anyway

**Closed as completed by Forstride** 2024-05-05 01:00 UTC
Labels: crash
