### ISSUE TITLE
BOP 1.8.9 Missing Biome Saplings Grow Into Oak Trees

### ISSUE THREAD

**Issue by Sn34kyP4nd4** [Glitchfiend/BiomesOPlenty#639] opened 2016-01-24 19:36 UTC
Was hoping it might be possible to make the missing biome saplings grow properly to allow access to the missing wood types before the remaining biomes are re-added.

**Comment by IndigoAvemour** [comment] 2016-01-27 13:27
I'm having this issue as well. I hate not being able to grow certain woods I need. :(

**Comment by Sn34kyP4nd4** [comment] 2016-01-31 15:30
As a temporary solution on my server we filled up some double chests with all the "common" wood types via creative and established a fair exchange. Some new saplings that still work are fir, dead, bamboo, and cherry.

**Comment by Adubbz** [comment] 2016-02-01 09:16
This is a dupe of https://github.com/Glitchfiend/BiomesOPlenty/issues/517. We don't actually add the trees until they are needed by a biome so we can see whether we want to make any adjustments whilst we are at it. We try to make sure our trees look good in masses as well as on their own, and it's hard to do that without the actual biome added.

**Closed by Adubbz** 2016-02-01 09:16 UTC
