### ISSUE TITLE
Recipe not there

### ISSUE THREAD

**Issue by GF4711** [Glitchfiend/BiomesOPlenty#1215] opened 2018-03-27 19:01 UTC
This issue occurs with Minecraft 1.12. 2
Forge is updated to the latest available version. 1.12.2 - 14.23.2.2611

*Attempting connection with missing mods [applecore, biomesoplenty, chameleon, extendedrenderer, coroutil, configmod, grue, hungeroverhaul, roguelike, storagedrawers, weather2] at SERVER
[20:59:17] [main/INFO]: Connecting to XXX
[20:59:19] [Netty Client IO #1/INFO]: Server protocol version 2
[20:59:19] [Netty Client IO #1/INFO]: Attempting connection with missing mods [applecore, biomesoplenty, chameleon, extendedrenderer, coroutil, configmod, grue, hungeroverhaul, roguelike, storagedrawers, weather2] at SERVER
[20:59:19] [Netty Client IO #1/INFO]: Injecting existing registry data into this client instance
[20:59:19] [Netty Client IO #1/INFO]: Applying holder lookups
[20:59:19] [Netty Client IO #1/INFO]: Holder lookups applied
[20:59:19] [Netty Client IO #1/INFO]: [Netty Client IO #1] Client side modded connection established
[20:59:20] [main/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Attempted to get the ID for a unknown recipe: net.minecraft.item.crafting.ShapedRecipes@732e9d36 Name: biomesoplenty:redwood_fence
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.IllegalArgumentException: Attempted to get the ID for a unknown recipe: net.minecraft.item.crafting.ShapedRecipes@732e9d36 Name: biomesoplenty:redwood_fence
	at net.minecraft.stats.RecipeBook.func_194075_d(RecipeBook.java:53) ~[ql.class:?]
	at net.minecraft.stats.RecipeBook.func_193830_f(RecipeBook.java:35) ~[ql.class:?]
	at net.minecraft.client.gui.recipebook.RecipeList.func_194214_a(SourceFile:27) ~[bns.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.lambda$handleRecipeBook$2(NetHandlerPlayClient.java:1487) ~[brz.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient$$Lambda$152/152902995.accept(Unknown Source) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_25]
	at net.minecraft.client.network.NetHandlerPlayClient.func_191980_a(NetHandlerPlayClient.java:1485) ~[brz.class:?]
	at net.minecraft.network.play.server.SPacketRecipeBook.func_148833_a(SourceFile:39) ~[js.class:?]
	at net.minecraft.network.play.server.SPacketRecipeBook.func_148833_a(SourceFile:12) ~[js.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more

**Comment by Syndaryl** [comment] 2018-03-28 02:29
"Attempting connection with missing mods [applecore, biomesoplenty,
chameleon, extendedrenderer, coroutil, configmod, grue, hungeroverhaul,
roguelike, storagedrawers, weather2] at SERVER "

You have a significantly different mod list from the server. That's gonna
give you trouble.

**Comment by Forstride** [comment] 2018-04-07 08:33
Can't reproduce this at all, and it could very well be caused by what Syndaryl pointed out.  Just gonna close this for now.

**Closed by Forstride** 2018-04-07 08:33 UTC
