### ISSUE TITLE
Whenever I Get An Item, The Texture Of The Item Isn't There And It Looks Like A Broken Computer Screen.

### ISSUE THREAD

**Issue by Ethantie** [Glitchfiend/BiomesOPlenty#1672] opened 2020-09-04 14:56 UTC
Read the Title.

**Comment by Forstride** [comment] 2020-09-04 15:44
You have not provided any useful info at all.  Closing this for the time being until more info is provided, but the issue is almost certainly unrelated to BOP.

**Closed by Forstride** 2020-09-04 15:44 UTC
Labels: bug-minor
