### ISSUE TITLE
Flowering Leaves Texture Issue

### ISSUE THREAD

**Issue by SilverHaloCM** [Glitchfiend/BiomesOPlenty#869] opened 2016-10-07 19:48 UTC
#### Issue Description:
For some reason, the texture for the Flowering Leaves isn't displaying as it should. This is without any texture packs, no OptiFine, using Biomes O' Plenty on its own.

#### Additional Information:

- fml-client-latest.log: https://www.dropbox.com/s/l50uf7qhe6jdeci/fml-client-latest.log?dl=0
- Screenshots:

![2016-10-07_15 15 58](https://cloud.githubusercontent.com/assets/22687267/19203235/28045cea-8ca4-11e6-95ed-fd30d799d4ad.png)
![2016-10-07_15 16 10](https://cloud.githubusercontent.com/assets/22687267/19203236/28059d08-8ca4-11e6-95c5-5a8c6ede7934.png)
![2016-10-07_15 16 21](https://cloud.githubusercontent.com/assets/22687267/19203237/2805e362-8ca4-11e6-9e5d-ac95aa842dd3.png)

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: 1.10.2 - 5.0.0.2086 (same issue in 5.0.0.2068 )
- Minecraft: 1.10.2
- Forge: 12.18.1.2095

**Comment by GirafiStudios** [comment] 2016-10-07 19:51
Duplicate of https://github.com/Glitchfiend/BiomesOPlenty/issues/696

**Closed** 2016-10-07 20:29 UTC
