### ISSUE TITLE
[Feature Request] Signs for the different types of wood should be added

### ISSUE THREAD

**Issue by DarthCaesium** [Glitchfiend/BiomesOPlenty#1868] opened 2021-06-07 13:03 UTC
For some reason, currently you cannot make signs out of this mod's wood. For example, you cannot make a Fir Sign or a Willow Sign. Seeing as other mods that add wood types of their own include variant wood signs, and also seeing that such a feature exists in vanilla Minecraft already, it would make sense to do so.

**Comment by Kitteh6660** [comment] 2021-09-22 23:42
A duplicate of #1633 but I agree. And it's not quite hard to add actually.

**Closed** 2022-12-10 12:13 UTC
Labels: feature
