### ISSUE TITLE
Random Crash with 1.8.9 3.0.0.1626 version

### ISSUE THREAD

**Issue by zedner** [Glitchfiend/BiomesOPlenty#596] opened 2016-01-12 02:56 UTC
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ThaumcraftLoader (Thaumcraft-1.8.9-5.1.1.jar)
  LoadingPlugin (FastLeaveDecay-1.2.jar)
  FMLPlugin (InventoryTweaks-1.60-dev-28.jar)
  NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 12.1.16. 03.54
Description: Getting biome

java.lang.ArrayIndexOutOfBoundsException: 143
	at biomesoplenty.common.world.layer.GenLayerClimate.func_75904_a(GenLayerClimate.java:36)
	at biomesoplenty.common.world.layer.GenLayerBiomeBOP.func_75904_a(GenLayerBiomeBOP.java:41)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:19)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:19)
	at biomesoplenty.common.world.layer.GenLayerBiomeEdgeBOP.func_75904_a(GenLayerBiomeEdgeBOP.java:30)
	at biomesoplenty.common.world.layer.GenLayerSubBiomesBOP.func_75904_a(GenLayerSubBiomesBOP.java:31)
	at biomesoplenty.common.world.layer.GenLayerBiomeIslands.func_75904_a(GenLayerBiomeIslands.java:32)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:19)
	at biomesoplenty.common.world.layer.GenLayerRaggedEdges.func_75904_a(GenLayerRaggedEdges.java:27)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:19)
	at net.minecraft.world.gen.layer.GenLayerShore.func_75904_a(SourceFile:15)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:19)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:19)
	at net.minecraft.world.gen.layer.GenLayerSmooth.func_75904_a(SourceFile:15)
	at biomesoplenty.common.world.layer.GenLayerRiverMixBOP.func_75904_a(GenLayerRiverMixBOP.java:39)
	at net.minecraft.world.gen.layer.GenLayerVoronoiZoom.func_75904_a(SourceFile:22)
	at net.minecraft.world.biome.WorldChunkManager.func_76931_a(WorldChunkManager.java:166)
	at net.minecraft.world.biome.BiomeCache$Block.<init>(SourceFile:28)
	at net.minecraft.world.biome.BiomeCache.func_76840_a(SourceFile:53)
	at net.minecraft.world.biome.BiomeCache.func_180284_a(SourceFile:62)
	at net.minecraft.world.biome.WorldChunkManager.func_180300_a(WorldChunkManager.java:61)
	at net.minecraft.world.chunk.Chunk.func_177411_a(Chunk.java:1300)
	at net.minecraft.world.World.getBiomeGenForCoordsBody(World.java:145)
	at net.minecraft.world.WorldProvider.getBiomeGenForCoords(WorldProvider.java:373)
	at net.minecraft.world.World.func_180494_b(World.java:134)
	at net.minecraft.world.ChunkCache.func_180494_b(ChunkCache.java:108)
	at net.minecraft.world.biome.BiomeColorHelper.func_180285_a(BiomeColorHelper.java:41)
	at net.minecraft.world.biome.BiomeColorHelper.func_180287_b(BiomeColorHelper.java:57)
	at net.minecraft.block.BlockLeaves.func_180662_a(BlockLeaves.java:56)
	at net.minecraft.block.BlockOldLeaf.func_180662_a(BlockOldLeaf.java:72)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelStandardQuads(BlockModelRenderer.java:470)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelStandard(BlockModelRenderer.java:198)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:61)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178259_a(BlockModelRenderer.java:50)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:109)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:281)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:38)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at biomesoplenty.common.world.layer.GenLayerClimate.func_75904_a(GenLayerClimate.java:36)
	at biomesoplenty.common.world.layer.GenLayerBiomeBOP.func_75904_a(GenLayerBiomeBOP.java:41)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:19)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:19)
	at biomesoplenty.common.world.layer.GenLayerBiomeEdgeBOP.func_75904_a(GenLayerBiomeEdgeBOP.java:30)
	at biomesoplenty.common.world.layer.GenLayerSubBiomesBOP.func_75904_a(GenLayerSubBiomesBOP.java:31)
	at biomesoplenty.common.world.layer.GenLayerBiomeIslands.func_75904_a(GenLayerBiomeIslands.java:32)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:19)
	at biomesoplenty.common.world.layer.GenLayerRaggedEdges.func_75904_a(GenLayerRaggedEdges.java:27)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:19)
	at net.minecraft.world.gen.layer.GenLayerShore.func_75904_a(SourceFile:15)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:19)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:19)
	at net.minecraft.world.gen.layer.GenLayerSmooth.func_75904_a(SourceFile:15)
	at biomesoplenty.common.world.layer.GenLayerRiverMixBOP.func_75904_a(GenLayerRiverMixBOP.java:39)
	at net.minecraft.world.gen.layer.GenLayerVoronoiZoom.func_75904_a(SourceFile:22)
	at net.minecraft.world.biome.WorldChunkManager.func_76931_a(WorldChunkManager.java:166)
	at net.minecraft.world.biome.BiomeCache$Block.<init>(SourceFile:28)
	at net.minecraft.world.biome.BiomeCache.func_76840_a(SourceFile:53)
	at net.minecraft.world.biome.BiomeCache.func_180284_a(SourceFile:62)
	at net.minecraft.world.biome.WorldChunkManager.func_180300_a(WorldChunkManager.java:61)
	at net.minecraft.world.chunk.Chunk.func_177411_a(Chunk.java:1300)

-- Coordinates of biome request --
Details:
	Location: World: (-353,129,289), Chunk: (at 15,8,1 in -23,18; contains blocks -368,0,288 to -353,255,303), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at net.minecraft.world.World.getBiomeGenForCoordsBody(World.java:145)
	at net.minecraft.world.WorldProvider.getBiomeGenForCoords(WorldProvider.java:373)
	at net.minecraft.world.World.func_180494_b(World.java:134)
	at net.minecraft.world.ChunkCache.func_180494_b(ChunkCache.java:108)
	at net.minecraft.world.biome.BiomeColorHelper.func_180285_a(BiomeColorHelper.java:41)
	at net.minecraft.world.biome.BiomeColorHelper.func_180287_b(BiomeColorHelper.java:57)
	at net.minecraft.block.BlockLeaves.func_180662_a(BlockLeaves.java:56)
	at net.minecraft.block.BlockOldLeaf.func_180662_a(BlockOldLeaf.java:72)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelStandardQuads(BlockModelRenderer.java:470)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelStandard(BlockModelRenderer.java:198)

-- Block model being tesselated --
Details:
	Block: minecraft:leaves[check_decay=false,decayable=true,variant=oak]
	Block location: World: (-352,129,288), Chunk: (at 0,8,0 in -22,18; contains blocks -352,0,288 to -337,255,303), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Using AO: false
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:61)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178259_a(BlockModelRenderer.java:50)

-- Block being tesselated --
Details:
	Block type: ID #18 (tile.leaves // net.minecraft.block.BlockOldLeaf)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-352,129,288), Chunk: (at 0,8,0 in -22,18; contains blocks -352,0,288 to -337,255,303), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:109)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Zednerr'/407, l='MpServer', x=-161.44, y=91.00, z=281.24]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: -188.00,64.00,256.00 - World: (-188,64,256), Chunk: (at 4,4,0 in -12,16; contains blocks -192,0,256 to -177,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 464047 game time, 487697 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 155 total; [EntityChicken['Chicken'/256, l='MpServer', x=-152.81, y=89.00, z=277.59], EntityItem['item.item.egg'/260, l='MpServer', x=-149.44, y=89.00, z=280.13], EntityCow['Cow'/261, l='MpServer', x=-155.09, y=89.00, z=272.47], EntityCow['Cow'/262, l='MpServer', x=-157.31, y=89.00, z=266.25], EntityChicken['Chicken'/263, l='MpServer', x=-153.69, y=89.00, z=265.66], EntityItem['item.item.egg'/19720, l='MpServer', x=-152.84, y=89.00, z=277.44], EntityItem['item.item.egg'/9489, l='MpServer', x=-150.66, y=89.00, z=280.88], EntityAuraNode['Aura Node'/277, l='MpServer', x=-141.50, y=24.50, z=255.50], EntityRabbit['Rabbit'/279, l='MpServer', x=-128.81, y=144.00, z=249.19], EntityRabbit['Rabbit'/280, l='MpServer', x=-131.72, y=146.00, z=251.19], EntitySkeleton['Skeleton'/25368, l='MpServer', x=-163.50, y=53.00, z=342.50], EntityBat['Bat'/21273, l='MpServer', x=-109.50, y=16.10, z=276.25], EntityChicken['Chicken'/282, l='MpServer', x=-139.00, y=143.00, z=265.75], EntityChicken['Chicken'/283, l='MpServer', x=-142.31, y=144.00, z=265.47], EntityChicken['Chicken'/284, l='MpServer', x=-131.06, y=136.00, z=267.47], EntityAuraNode['Aura Node'/28, l='MpServer', x=-298.50, y=35.50, z=265.50], EntityChicken['Chicken'/285, l='MpServer', x=-129.50, y=143.00, z=263.50], EntityItem['item.item.egg'/20766, l='MpServer', x=-156.88, y=89.00, z=267.50], EntityBat['Bat'/12319, l='MpServer', x=-161.25, y=25.41, z=313.88], EntityBat['Bat'/23583, l='MpServer', x=-107.54, y=22.97, z=299.43], EntityChicken['Chicken'/290, l='MpServer', x=-136.69, y=146.00, z=258.63], EntityZombie['Zombie'/24866, l='MpServer', x=-237.50, y=61.00, z=336.50], EntityAuraNode['Aura Node'/35, l='MpServer', x=-273.50, y=110.50, z=175.50], EntitySkeleton['Skeleton'/21539, l='MpServer', x=-116.50, y=21.00, z=354.50], EntitySpider['Spider'/23335, l='MpServer', x=-89.50, y=47.00, z=343.50], EntityRabbit['Rabbit'/296, l='MpServer', x=-142.31, y=63.00, z=324.41], EntityBat['Bat'/22057, l='MpServer', x=-201.59, y=23.51, z=241.00], EntitySkeleton['Skeleton'/24873, l='MpServer', x=-135.50, y=16.00, z=296.50], EntityRabbit['Rabbit'/298, l='MpServer', x=-132.97, y=63.00, z=335.75], EntityCreeper['Creeper'/21035, l='MpServer', x=-219.50, y=41.00, z=243.50], EntitySpider['Spider'/22829, l='MpServer', x=-201.50, y=24.00, z=234.50], EntityChicken['Chicken'/307, l='MpServer', x=-119.59, y=143.00, z=255.59], EntityZombie['Zombie'/23347, l='MpServer', x=-110.50, y=13.00, z=280.50], EntityRabbit['Rabbit'/309, l='MpServer', x=-127.50, y=154.00, z=252.50], EntityAuraNode['Aura Node'/55, l='MpServer', x=-284.50, y=93.50, z=369.50], EntityAuraNode['Aura Node'/56, l='MpServer', x=-282.50, y=115.50, z=397.50], EntityChicken['Chicken'/314, l='MpServer', x=-127.50, y=135.00, z=267.59], EntityChicken['Chicken'/316, l='MpServer', x=-127.50, y=144.00, z=261.50], EntityZombie['Zombie'/25408, l='MpServer', x=-130.50, y=14.00, z=309.50], EntityItem['item.item.egg'/11329, l='MpServer', x=-209.63, y=136.00, z=218.16], EntitySkeleton['Skeleton'/25409, l='MpServer', x=-130.50, y=13.00, z=277.50], EntityZombie['Zombie'/24900, l='MpServer', x=-119.50, y=26.00, z=224.50], EntityAuraNode['Aura Node'/325, l='MpServer', x=-103.50, y=75.50, z=186.50], EntityZombie['Zombie'/13639, l='MpServer', x=-109.50, y=29.00, z=309.50], EntityCreeper['Creeper'/23883, l='MpServer', x=-84.50, y=48.00, z=348.50], EntityCreeper['Creeper'/18765, l='MpServer', x=-196.50, y=25.00, z=252.50], EntityCreeper['Creeper'/19789, l='MpServer', x=-229.50, y=7.00, z=331.50], EntityItem['item.item.egg'/21326, l='MpServer', x=-141.84, y=144.00, z=265.38], EntityItem['item.item.egg'/17232, l='MpServer', x=-126.97, y=144.00, z=261.13], EntityItem['item.item.egg'/24919, l='MpServer', x=-223.81, y=115.00, z=325.47], EntityCreeper['Creeper'/16984, l='MpServer', x=-219.50, y=56.00, z=330.50], EntityAuraNode['Aura Node'/347, l='MpServer', x=-90.50, y=65.50, z=369.50], EntityAuraNode['Aura Node'/348, l='MpServer', x=-65.50, y=116.50, z=146.50], EntityBat['Bat'/14940, l='MpServer', x=-116.59, y=23.10, z=300.25], EntityChicken['Chicken'/93, l='MpServer', x=-240.56, y=112.00, z=264.59], EntitySpider['Spider'/24925, l='MpServer', x=-201.50, y=17.00, z=203.50], EntityZombie['Zombie'/23393, l='MpServer', x=-132.50, y=39.00, z=329.50], EntityAuraNode['Aura Node'/99, l='MpServer', x=-252.50, y=43.50, z=424.50], EntitySkeleton['Skeleton'/23397, l='MpServer', x=-171.50, y=67.00, z=335.50], EntityAuraNode['Aura Node'/358, l='MpServer', x=-53.50, y=69.50, z=159.50], EntityAuraNode['Aura Node'/359, l='MpServer', x=-50.50, y=80.50, z=284.50], EntityZombie['Zombie'/22376, l='MpServer', x=-210.50, y=68.00, z=286.50], EntityCreeper['Creeper'/20587, l='MpServer', x=-229.59, y=14.00, z=225.72], EntityBat['Bat'/21099, l='MpServer', x=-158.66, y=30.84, z=347.81], EntityChicken['Chicken'/108, l='MpServer', x=-238.81, y=114.00, z=268.50], EntityChicken['Chicken'/109, l='MpServer', x=-229.81, y=125.00, z=269.56], EntityChicken['Chicken'/110, l='MpServer', x=-232.50, y=127.00, z=266.03], EntityItem['item.item.egg'/12142, l='MpServer', x=-130.97, y=136.00, z=267.13], EntityChicken['Chicken'/111, l='MpServer', x=-238.47, y=113.00, z=258.41], EntityChicken['Chicken'/112, l='MpServer', x=-238.69, y=115.00, z=266.59], EntityBat['Bat'/19313, l='MpServer', x=-87.13, y=33.25, z=267.78], EntityAuraNode['Aura Node'/371, l='MpServer', x=-44.50, y=72.50, z=174.50], EntityChicken['Chicken'/116, l='MpServer', x=-229.41, y=109.00, z=285.66], EntityChicken['Chicken'/117, l='MpServer', x=-226.53, y=111.00, z=283.00], EntityChicken['Chicken'/119, l='MpServer', x=-239.41, y=114.00, z=266.28], EntitySkeleton['Skeleton'/23674, l='MpServer', x=-200.50, y=22.00, z=238.50], EntityAuraNode['Aura Node'/381, l='MpServer', x=-23.50, y=39.50, z=202.50], EntityZombie['Zombie'/23166, l='MpServer', x=-128.50, y=21.00, z=259.50], EntityChicken['Chicken'/127, l='MpServer', x=-220.03, y=118.00, z=348.47], EntityAuraNode['Aura Node'/383, l='MpServer', x=-31.50, y=63.50, z=283.50], EntityChicken['Chicken'/128, l='MpServer', x=-236.38, y=122.00, z=350.63], EntityAuraNode['Aura Node'/136, l='MpServer', x=-223.50, y=111.50, z=145.50], EntityItem['item.item.egg'/24712, l='MpServer', x=-152.88, y=89.00, z=276.03], EntityCreeper['Creeper'/19593, l='MpServer', x=-218.50, y=44.00, z=307.50], EntitySpider['Spider'/23946, l='MpServer', x=-147.31, y=28.09, z=254.28], EntityChicken['Chicken'/139, l='MpServer', x=-218.50, y=138.00, z=206.50], EntityChicken['Chicken'/140, l='MpServer', x=-217.50, y=137.00, z=203.66], EntityChicken['Chicken'/142, l='MpServer', x=-220.50, y=152.00, z=206.50], EntityChicken['Chicken'/143, l='MpServer', x=-210.16, y=137.00, z=218.53], EntityItem['item.item.egg'/17312, l='MpServer', x=-180.84, y=106.00, z=223.63], EntityChicken['Chicken'/164, l='MpServer', x=-223.38, y=115.00, z=325.53], EntityZombie['Zombie'/23460, l='MpServer', x=-120.50, y=26.00, z=256.50], EntityBat['Bat'/24740, l='MpServer', x=-96.33, y=48.50, z=344.44], EntityZombie['Zombie'/23719, l='MpServer', x=-164.50, y=24.00, z=317.50], EntityAuraNode['Aura Node'/168, l='MpServer', x=-208.50, y=86.50, z=356.50], EntitySkeleton['Skeleton'/23720, l='MpServer', x=-101.53, y=25.00, z=290.84], EntityZombie['Zombie'/24232, l='MpServer', x=-84.50, y=25.00, z=206.50], EntityCreeper['Creeper'/17834, l='MpServer', x=-134.50, y=33.00, z=325.50], EntityChicken['Chicken'/171, l='MpServer', x=-220.75, y=111.00, z=358.34], EntityZombie['Zombie'/21675, l='MpServer', x=-124.94, y=21.00, z=336.50], EntityChicken['Chicken'/172, l='MpServer', x=-219.13, y=115.00, z=352.47], EntityBat['Bat'/22447, l='MpServer', x=-131.50, y=30.81, z=237.59], EntityChicken['Chicken'/177, l='MpServer', x=-193.72, y=103.00, z=210.50], EntityChicken['Chicken'/178, l='MpServer', x=-197.69, y=103.00, z=217.19], EntityCreeper['Creeper'/22962, l='MpServer', x=-239.50, y=62.00, z=333.50], EntityCreeper['Creeper'/24242, l='MpServer', x=-157.50, y=49.00, z=335.50], EntityChicken['Chicken'/181, l='MpServer', x=-199.50, y=114.00, z=223.28], EntityChicken['Chicken'/182, l='MpServer', x=-202.53, y=119.00, z=226.50], EntityChicken['Chicken'/185, l='MpServer', x=-203.44, y=125.00, z=292.63], EntityChicken['Chicken'/186, l='MpServer', x=-205.44, y=121.00, z=294.53], EntityZombie['Zombie'/21691, l='MpServer', x=-198.50, y=38.00, z=291.50], EntityPlayerSP['Zednerr'/407, l='MpServer', x=-161.44, y=91.00, z=281.24], EntityBat['Bat'/24510, l='MpServer', x=-90.84, y=22.03, z=308.16], EntityItem['item.item.egg'/16321, l='MpServer', x=-128.94, y=143.00, z=263.53], EntityChicken['Chicken'/196, l='MpServer', x=-180.50, y=106.00, z=223.63], EntityChicken['Chicken'/197, l='MpServer', x=-187.44, y=97.00, z=219.38], EntityZombie['Zombie'/6105, l='MpServer', x=-179.47, y=87.00, z=299.94], EntityZombie['Zombie'/25051, l='MpServer', x=-224.50, y=55.00, z=322.50], EntityAuraNode['Aura Node'/223, l='MpServer', x=-173.50, y=113.50, z=199.50], EntityZombie['Zombie'/20447, l='MpServer', x=-105.50, y=27.00, z=301.50], EntitySquid['Squid'/21474, l='MpServer', x=-112.50, y=60.00, z=300.50], EntityRabbit['Rabbit'/229, l='MpServer', x=-167.09, y=67.00, z=340.22], EntitySpider['Spider'/25061, l='MpServer', x=-226.50, y=7.00, z=282.50], EntityAuraNode['Aura Node'/231, l='MpServer', x=-166.50, y=33.50, z=392.50], EntityCreeper['Creeper'/23015, l='MpServer', x=-107.50, y=29.00, z=259.50], EntityAuraNode['Aura Node'/232, l='MpServer', x=-173.50, y=86.50, z=424.50], EntityCreeper['Creeper'/23017, l='MpServer', x=-219.56, y=90.00, z=280.00], EntityCreeper['Creeper'/23787, l='MpServer', x=-108.00, y=12.00, z=288.56], EntityCow['Cow'/236, l='MpServer', x=-156.65, y=89.00, z=269.11], EntityCow['Cow'/237, l='MpServer', x=-152.28, y=89.00, z=269.69], EntitySpider['Spider'/24558, l='MpServer', x=-107.06, y=63.09, z=207.28], EntityCow['Cow'/239, l='MpServer', x=-152.75, y=89.00, z=272.75], EntityChicken['Chicken'/240, l='MpServer', x=-150.66, y=89.00, z=279.44], EntityChicken['Chicken'/241, l='MpServer', x=-150.09, y=89.00, z=280.78], EntityChicken['Chicken'/242, l='MpServer', x=-150.25, y=89.00, z=280.16], EntitySheep['Sheep'/243, l='MpServer', x=-155.44, y=89.00, z=280.25], EntitySheep['Sheep'/244, l='MpServer', x=-157.56, y=89.00, z=279.47], EntityItem['item.item.egg'/9204, l='MpServer', x=-118.97, y=143.00, z=256.22], EntityBat['Bat'/19956, l='MpServer', x=-84.28, y=49.01, z=346.36], EntitySheep['Sheep'/245, l='MpServer', x=-157.47, y=89.00, z=276.16], EntityChicken['Chicken'/246, l='MpServer', x=-151.22, y=89.00, z=279.34], EntityCreeper['Creeper'/22774, l='MpServer', x=-135.50, y=28.00, z=241.03], EntityBat['Bat'/25078, l='MpServer', x=-139.22, y=21.50, z=314.53], EntityChicken['Chicken'/247, l='MpServer', x=-150.56, y=89.00, z=275.66], EntityChicken['Chicken'/248, l='MpServer', x=-149.67, y=89.00, z=279.63], EntitySheep['Sheep'/249, l='MpServer', x=-155.69, y=89.00, z=279.16], EntityCreeper['Creeper'/22521, l='MpServer', x=-150.50, y=63.00, z=263.50], EntityChicken['Chicken'/250, l='MpServer', x=-149.22, y=89.00, z=280.78], EntitySheep['Sheep'/251, l='MpServer', x=-156.56, y=89.00, z=280.53], EntitySkeleton['Skeleton'/24315, l='MpServer', x=-232.50, y=23.00, z=359.50], EntitySheep['Sheep'/252, l='MpServer', x=-154.47, y=89.00, z=279.09], EntityChicken['Chicken'/253, l='MpServer', x=-150.93, y=89.00, z=280.09], EntityChicken['Chicken'/254, l='MpServer', x=-149.22, y=89.00, z=280.16], EntityChicken['Chicken'/255, l='MpServer', x=-151.41, y=89.00, z=280.10], EntityCreeper['Creeper'/23295, l='MpServer', x=-227.50, y=62.00, z=325.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:404)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:44)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 7 (amd64) version 6.1
	CPU: 4x AMD A10-5800K APU with Radeon(tm) HD Graphics 
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 265297072 bytes (253 MB) / 1012195328 bytes (965 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 70, allocated: 1, tallocated: 107
	FML: MCP 9.19 Powered by Forge 11.15.0.1688 Optifine OptiFine_1.8.9_HD_U_H1 24 mods loaded, 24 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.18} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.0.1688.jar) 
	UCHIJAAAA	Forge{11.15.0.1688} [Minecraft Forge] (forge-1.8.9-11.15.0.1688.jar) 
	UCHIJAAAA	BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8.9-3.0.0.1626-universal.jar) 
	UCHIJAAAA	chiselsandbits{@version@} [Chisels & Bits] (chiselsandbits-mc1.8.9-v1.8-beta8.jar) 
	UCHIJAAAA	craftingcraft{2.0.6} [CraftingCraft] (craftingcraft-mc1.8.9-2.0.6.jar) 
	UCHIJAAAA	CustomBackgrounds{1.0} [Custom Backgrounds] (CustomBackgrounds-1.0.jar) 
	UCHIJAAAA	FastLeaveDecay{1.1} [Fast Leave Decay] (FastLeaveDecay-1.2.jar) 
	UCHIJAAAA	flatcoloredblocks{mc1.8.9-v1.3} [Flat Colored Blocks] (flatcoloredblocks-mc1.8.9-v1.5.jar) 
	UCHIJAAAA	furnus{1.3} [Furnus] (Furnus-1.8.9-1.3.jar) 
	UCHIJAAAA	inventorytweaks{1.60-dev-28-3253249} [Inventory Tweaks] (InventoryTweaks-1.60-dev-28.jar) 
	UCHIJAAAA	ironbackpacks{1.8-1.0.7} [Iron Backpacks] (IronBackpacks-1.8-1.0.7.jar) 
	UCHIJAAAA	JEI{2.16.1.77} [Just Enough Items] (jei_1.8.9-2.16.1.77.jar) 
	UCHIJAAAA	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UCHIJAAAA	Thaumcraft{5.1.1} [Thaumcraft] (Thaumcraft-1.8.9-5.1.1.jar) 
	UCHIJAAAA	JEIAddons{0.8.1.30} [Just Enough Items Addons] (JEIAddons_1.8.9-0.8.1.30.jar) 
	UCHIJAAAA	LunatriusCore{1.1.2.32} [LunatriusCore] (LunatriusCore-1.8.9-1.1.2.32-universal.jar) 
	UCHIJAAAA	mantle{1.8.8-0.6.jenkins60} [Mantle] (Mantle-1.8.8-0.6.jar) 
	UCHIJAAAA	MultiPageChest{1.4.0} [Multi Page Chest] (MultiPageChest-1.4.0-MC1.8.9.jar) 
	UCHIJAAAA	notenoughwands{1.2.4} [Not Enough Wands] (notenoughwands-1.8.9-1.2.4.jar) 
	UCHIJAAAA	redstonepaste{1.7.2} [Redstone Paste] (redstonepaste-mc1.8.8-1.7.2.jar) 
	UCHIJAAAA	SimilsaxTranstructors{1.8.8.16} [Similsax Transtructors] (SimilsaxTranstructors-1.8.8.16.jar) 
	UCHIJAAAA	tconstruct{1.8.8-2.0.1} [Tinkers' Construct] (TConstruct-1.8.8-2.0.1.jar) 
	UCHIJAAAA	uncraftingtable{1.0.2} [Uncrafting Grinder] (UncraftingGrinder-1.8.9-1.0.2.jar) 
	Loaded coremods (and transformers): 
ThaumcraftLoader (Thaumcraft-1.8.9-5.1.1.jar)
  
LoadingPlugin (FastLeaveDecay-1.2.jar)
  lumien.fastleavedecay.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.60-dev-28.jar)
  invtweaks.forge.asm.ContainerTransformer
NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
  net.fybertech.nwr.NowWithRendering
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerMaterials (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerDebug (Enabled/Not Forced)

	Launched Version: 1.8.9-forge1.8.9-11.15.0.1688
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Unity-Complete-1.2.0.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A10-5800K APU with Radeon(tm) HD Graphics

**Comment by Adubbz** [comment] 2016-01-12 03:10
Duplicate of #535

**Closed by Adubbz** 2016-01-12 03:10 UTC

**Comment by Adubbz** [comment] 2016-01-12 04:59
Hrm, out of curiosity, did you use any custom world settings in the world you got this crash with? I have seen it happen, however I haven't been able to get it consistently to figure out why it's happening

**Comment by zedner** [comment] 2016-01-12 08:32
no but i created this world with older version of BoP (1620) before i got
crash on that world with new version (1626)

**Comment by zedner** [comment] 2016-01-12 08:42
oh yeah i just disabled gems generation in custom options

**Comment by Adubbz** [comment] 2016-01-12 09:41
This should hopefully be fixed now

**Comment by zedner** [comment] 2016-01-12 10:00
okay i hope i was helpful and thank you for this great mod
