### ISSUE TITLE
Biomes O' Plenty (biomesoplenty) encountered an error during the load_registries event phase (1.16.3)

### ISSUE THREAD

**Issue by k69xx** [Glitchfiend/BiomesOPlenty#1722] opened 2020-10-27 13:00 UTC
## Bug Report

Biomes O' Plenty (biomesoplenty) encountered an error during the load_registries event phase 
### How can the crash be reproduced?

So I press the launch button and BOP won't load properly 
![image](https://user-images.githubusercontent.com/73535899/97304561-f459ea00-186c-11eb-9133-cb0fb96c9ba5.png)

### Crash Report and Logs
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 27.10.20 15:46
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:494) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$4471/99759097.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:418) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:490) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$4253/936924719.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:172) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:802) [?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.32.jar:34.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$445/353580491.call(Unknown Source) [forge-1.16.3-34.1.32.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.5.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.5.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.5.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-8.0.5.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-8.0.5.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:56) ~[?:?] {re:classloading}
-- MOD biomesoplenty --
Details:
	Caused by 0: java.lang.ExceptionInInitializerError
		at biomesoplenty.common.biome.overworld.TropicBeachBiome.configureGeneration(TropicBeachBiome.java:40) ~[?:?] {re:classloading}
		at biomesoplenty.common.biome.BiomeTemplate.build(BiomeTemplate.java:46) ~[?:?] {re:classloading}
		at biomesoplenty.common.biome.BiomeRegistry$TemplateRegistrationData.<init>(BiomeRegistry.java:477) ~[?:?] {re:classloading}
		at biomesoplenty.common.biome.BiomeRegistry$ToggleableStandardBiomeRegistrationData.<init>(BiomeRegistry.java:643) ~[?:?] {re:classloading}
		at biomesoplenty.common.biome.BiomeRegistry.deferTechnicalBiomeRegistration(BiomeRegistry.java:48) ~[?:?] {re:classloading}
		at biomesoplenty.init.ModBiomes.registerTechnicalBiome(ModBiomes.java:345) ~[?:?] {re:classloading}
		at biomesoplenty.init.ModBiomes.registerBiomes(ModBiomes.java:116) ~[?:?] {re:classloading}
		at net.minecraftforge.eventbus.ASMEventHandler_22_ModBiomes_registerBiomes_Register.invoke(.dynamic) ~[?:?] {}
		at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:34.1] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:111) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModContainer$$Lambda$3094/1430104337.run(Unknown Source) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
		at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:242) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:229) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:195) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$1(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
		at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2898/397639322.run(Unknown Source) ~[?:?] {}
		at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:123) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
		at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2899/1808470758.run(Unknown Source) ~[?:?] {}
		at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
		at net.minecraft.client.Minecraft.<init>(Minecraft.java:424) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
		at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
		at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
		at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.32.jar:34.1] {}
		at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$445/353580491.call(Unknown Source) [forge-1.16.3-34.1.32.jar:34.1] {}
		at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.5.jar:?] {}
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.5.jar:?] {}
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.5.jar:?] {}
		at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-8.0.5.jar:?] {}
		at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-8.0.5.jar:?] {}

	Mod File: BiomesOPlenty_1.16.3_12.0.0.409_universal.jar
	Failure message: Biomes O' Plenty (biomesoplenty) encountered an error during the load_registries event phase
		java.lang.ExceptionInInitializerError: null
	Mod Version: 1.16.3-12.0.0.409
	Mod Issue URL: https://github.com/Glitchfiend/BiomesOPlenty/issues
	Exception message: java.lang.IllegalStateException: Can not register to a locked registry. Modder should use Forge Register methods.
Stacktrace:
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:56) ~[?:?] {re:classloading}
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:72) ~[?:?] {re:classloading}
	at net.minecraftforge.registries.NamespacedWrapper.func_218381_a(NamespacedWrapper.java:40) ~[?:?] {re:classloading}
	at net.minecraft.util.registry.Registry.func_218322_a(Registry.java:456) ~[?:?] {re:classloading}
	at biomesoplenty.common.world.gen.surfacebuilders.BOPSurfaceBuilders.register(BOPSurfaceBuilders.java:55) ~[?:?] {re:classloading}
	at biomesoplenty.common.world.gen.surfacebuilders.BOPSurfaceBuilders.<clinit>(BOPSurfaceBuilders.java:35) ~[?:?] {re:classloading}
	at biomesoplenty.common.biome.overworld.TropicBeachBiome.configureGeneration(TropicBeachBiome.java:40) ~[?:?] {re:classloading}
	at biomesoplenty.common.biome.BiomeTemplate.build(BiomeTemplate.java:46) ~[?:?] {re:classloading}
	at biomesoplenty.common.biome.BiomeRegistry$TemplateRegistrationData.<init>(BiomeRegistry.java:477) ~[?:?] {re:classloading}
	at biomesoplenty.common.biome.BiomeRegistry$ToggleableStandardBiomeRegistrationData.<init>(BiomeRegistry.java:643) ~[?:?] {re:classloading}
	at biomesoplenty.common.biome.BiomeRegistry.deferTechnicalBiomeRegistration(BiomeRegistry.java:48) ~[?:?] {re:classloading}
	at biomesoplenty.init.ModBiomes.registerTechnicalBiome(ModBiomes.java:345) ~[?:?] {re:classloading}
	at biomesoplenty.init.ModBiomes.registerBiomes(ModBiomes.java:116) ~[?:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_22_ModBiomes_registerBiomes_Register.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:34.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:111) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3094/1430104337.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:242) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:229) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:195) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$1(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2898/397639322.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:123) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2899/1808470758.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:424) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.32.jar:34.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$445/353580491.call(Unknown Source) [forge-1.16.3-34.1.32.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.5.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.5.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.5.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-8.0.5.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-8.0.5.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3448273184 bytes (3288 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 6
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.5+84+master.3310fe0
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.3-34.1.32.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.32.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.3-34.1.32.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.32.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.3_HD_U_G3.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.3-34.1.32.jar fml TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.32
	FML Language Providers: 
		javafml@34.1
		minecraft@1
	Mod List: 
		forge-1.16.3-34.1.32-client.jar                   |Minecraft                     |minecraft                     |1.16.3              |COMMON_SET|NOSIGNATURE
		simplefarming-1.16.3-1.3.3.jar                    |Simple Farming                |simplefarming                 |1.16.3-1.3.3        |COMMON_SET|NOSIGNATURE
		JustEnoughResources-1.16.3-0.12.0.100.jar         |Just Enough Resources         |jeresources                   |0.12.0.100          |COMMON_SET|NOSIGNATURE
		CraftTweaker-1.16.3-7.0.0.48.jar                  |CraftTweaker                  |crafttweaker                  |7.0.0.48            |COMMON_SET|NOSIGNATURE
		forge-1.16.3-34.1.32-universal.jar                |Forge                         |forge                         |34.1.32             |COMMON_SET|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		BiomesOPlenty_1.16.3_12.0.0.409_universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.3-12.0.0.409   |VALIDATE  |NOSIGNATURE
		Xaeros_Minimap_20.26.0_Forge_1.16.3.jar           |Xaero's Minimap               |xaerominimap                  |20.26.0             |COMMON_SET|NOSIGNATURE
		furniture-7.0.0-pre19-1.16.3.jar                  |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre19         |COMMON_SET|NOSIGNATURE
		AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |COMMON_SET|NOSIGNATURE
		ironchest-1.16.3-11.2.6.jar                       |Iron Chests                   |ironchest                     |1.16.3-11.2.6       |COMMON_SET|NOSIGNATURE
		productivebees-1.16.3-0.4.1.4.jar                 |Productive Bees               |productivebees                |1.16.3-0.4.1.4      |COMMON_SET|NOSIGNATURE
		NaturesCompass-1.16.3-1.8.5.jar                   |Nature's Compass              |naturescompass                |1.16.3-1.8.5        |COMMON_SET|NOSIGNATURE
		jei-1.16.3-7.6.0.49.jar                           |Just Enough Items             |jei                           |7.5.0.43            |COMMON_SET|NOSIGNATURE
	Crash Report UUID: da492225-c7cc-4eff-ac3f-da58cda7aeec
	OptiFine Version: OptiFine_1.16.3_HD_U_G3
	OptiFine Build: 20200916-082411
	Render Distance Chunks: 21
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 451.67
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 6

### Mod Version
Here's the list of mods I'm currently using
![image](https://user-images.githubusercontent.com/73535899/97304819-5286cd00-186d-11eb-93c7-54a0750f7f3d.png)

**Comment by k69xx** [comment] 2020-10-27 13:24
I'im using the latest BOP version and the latest Forge version.

**Comment by Forstride** [comment] 2020-10-27 15:41
Duplicate of https://github.com/Glitchfiend/BiomesOPlenty/issues/1721

Downgrade Forge to 34.1.25 for the time being.

**Closed by Forstride** 2020-10-27 15:41 UTC
Labels: crash
