### ISSUE TITLE
Crash when pick block on BOP Grass

### ISSUE THREAD

**Issue by SteveKunG** [Glitchfiend/BiomesOPlenty#397] opened 2015-01-30 12:21 UTC
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 27/1/2558, 23:36 น.
Description: Rendering item

java.lang.ArrayIndexOutOfBoundsException: 8
	at biomesoplenty.common.blocks.BlockBOPNewGrass.func_149691_a(BlockBOPNewGrass.java:215)
	at net.minecraft.item.ItemBlockWithMetadata.func_77617_a(SourceFile:20)
	at net.minecraft.item.Item.func_77650_f(Item.java:440)
	at net.minecraft.item.ItemStack.func_77954_c(ItemStack.java:117)
	at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:403)
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)
	at net.minecraft.client.gui.GuiIngame.func_73832_a(GuiIngame.java:955)
	at net.minecraftforge.client.GuiIngameForge.renderHotbar(GuiIngameForge.java:206)
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:141)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1325)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at biomesoplenty.common.blocks.BlockBOPNewGrass.func_149691_a(BlockBOPNewGrass.java:215)
	at net.minecraft.item.ItemBlockWithMetadata.func_77617_a(SourceFile:20)
	at net.minecraft.item.Item.func_77650_f(Item.java:440)
	at net.minecraft.item.ItemStack.func_77954_c(ItemStack.java:117)
	at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:403)

-- Item being rendered --
Details:
	Item Type: biomesoplenty.common.itemblocks.ItemBlockBOPMetadata@1c172ec
	Item Aux: 4
	Item NBT: null
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)
	at net.minecraft.client.gui.GuiIngame.func_73832_a(GuiIngame.java:955)
	at net.minecraftforge.client.GuiIngameForge.renderHotbar(GuiIngameForge.java:206)
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:141)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['SteveMCCommander'/273, l='MpServer', x=-495.21, y=69.62, z=889.44]]
	Chunk stats: MultiplayerChunkCache: 289, 298
	Level seed: 0
	Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 48852 game time, 72614 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 86 total; [GCEntityClientPlayerMP['SteveMCCommander'/273, l='MpServer', x=-495.21, y=69.62, z=889.44], EntitySkeleton['Skeleton'/58510, l='MpServer', x=-480.50, y=36.00, z=916.50], EntitySpider['Spider'/51762, l='MpServer', x=-571.50, y=63.00, z=959.50], EntityZombie['Zombie'/51761, l='MpServer', x=-473.50, y=33.00, z=910.50], EntityCreeper['Creeper'/58110, l='MpServer', x=-504.66, y=38.00, z=945.94], EntityZombie['Zombie'/58514, l='MpServer', x=-549.50, y=11.00, z=868.50], EntityBat['Bat'/51501, l='MpServer', x=-558.25, y=25.00, z=850.75], EntityBat['Bat'/51502, l='MpServer', x=-552.38, y=24.42, z=849.53], EntityBat['Bat'/51499, l='MpServer', x=-573.69, y=20.00, z=849.63], EntitySpider['Spider'/22553, l='MpServer', x=-505.03, y=66.00, z=906.88], EntityCreeper['Creeper'/58559, l='MpServer', x=-453.50, y=22.00, z=883.50], EntityZombie['Zombie'/58551, l='MpServer', x=-438.50, y=33.00, z=956.50], EntityCreeper['Creeper'/58545, l='MpServer', x=-451.50, y=22.00, z=883.50], EntityGolemBobber['entity.Thaumcraft.GolemBobber.name'/58291, l='MpServer', x=-517.84, y=63.90, z=930.03], EntityBat['Bat'/58298, l='MpServer', x=-466.51, y=19.81, z=942.81], EntityBat['Bat'/58299, l='MpServer', x=-555.09, y=23.00, z=849.28], EntityZombie['Zombie'/51523, l='MpServer', x=-467.59, y=13.00, z=934.00], EntityCreeper['Creeper'/58560, l='MpServer', x=-451.50, y=22.00, z=885.50], EntityBat['Bat'/58300, l='MpServer', x=-464.53, y=39.10, z=902.25], EntityBat['Bat'/58301, l='MpServer', x=-453.25, y=39.10, z=910.25], EntityCreeper['Creeper'/56357, l='MpServer', x=-434.50, y=30.00, z=926.50], EntityBat['Bat'/48840, l='MpServer', x=-436.78, y=19.00, z=890.53], EntityBat['Bat'/51819, l='MpServer', x=-499.25, y=12.00, z=950.50], EntityZombie['Zombie'/36984, l='MpServer', x=-476.69, y=62.22, z=885.53], EntityCreeper['Creeper'/36982, l='MpServer', x=-476.47, y=62.46, z=884.16], EntitySkeleton['Skeleton'/55394, l='MpServer', x=-426.50, y=19.00, z=957.50], EntitySquid['Squid'/39898, l='MpServer', x=-464.06, y=46.97, z=854.03], EntitySkeleton['Skeleton'/55393, l='MpServer', x=-426.50, y=19.00, z=956.50], EntityChicken['Chicken'/95, l='MpServer', x=-563.44, y=68.00, z=958.44], EntitySkeleton['Skeleton'/55392, l='MpServer', x=-448.50, y=19.00, z=964.50], EntitySkeleton['Skeleton'/51540, l='MpServer', x=-422.50, y=19.00, z=939.50], EntityChicken['Chicken'/98, l='MpServer', x=-562.47, y=65.00, z=963.63], EntityChicken['Chicken'/96, l='MpServer', x=-551.56, y=69.00, z=957.44], EntityChicken['Chicken'/97, l='MpServer', x=-560.59, y=69.00, z=960.59], EntityCreeper['Creeper'/57790, l='MpServer', x=-459.50, y=14.00, z=941.50], EntityCreeper['Creeper'/57789, l='MpServer', x=-460.50, y=14.00, z=940.50], EntityCow['Cow'/109, l='MpServer', x=-550.91, y=65.00, z=944.06], EntityCaveSpider['Cave Spider'/41268, l='MpServer', x=-18.79, y=-32.62, z=45.56], EntityCreeper['Creeper'/53703, l='MpServer', x=-509.50, y=66.00, z=922.50], EntityGolemBase['Tallow Golem'/127, l='MpServer', x=-517.50, y=64.00, z=932.75], EntityGolemBase['Iron Golem'/126, l='MpServer', x=-515.31, y=64.00, z=928.91], EntityGolemBase['Straw Golem'/125, l='MpServer', x=-519.78, y=64.00, z=933.53], EntityGolemBase['Clay Golem'/122, l='MpServer', x=-518.13, y=62.00, z=930.53], EntityCow['Cow'/136, l='MpServer', x=-521.06, y=66.00, z=938.97], EntitySkeleton['Skeleton'/57960, l='MpServer', x=-447.50, y=20.00, z=877.50], EntityZombie['Zombie'/57962, l='MpServer', x=-552.50, y=15.00, z=851.50], EntityGolemBase['Iron Golem'/129, l='MpServer', x=-516.50, y=64.00, z=933.63], EntityGolemBase['Flesh Golem'/128, l='MpServer', x=-521.53, y=64.00, z=930.25], EntityCow['Cow'/131, l='MpServer', x=-505.47, y=66.00, z=904.63], EntityGolemBase['Wood Golem'/133, l='MpServer', x=-517.34, y=64.00, z=931.00], EntityGolemBase['Thaumium Golem'/132, l='MpServer', x=-518.63, y=64.00, z=934.47], EntityCreeper['Creeper'/51900, l='MpServer', x=-440.50, y=19.00, z=880.50], EntityGolemBase['Wood Golem'/135, l='MpServer', x=-518.91, y=64.00, z=932.50], EntityGolemBase['Tallow Golem'/134, l='MpServer', x=-518.25, y=64.00, z=931.00], EntitySkeleton['Skeleton'/58390, l='MpServer', x=-478.50, y=36.00, z=916.50], EntitySpider['Spider'/51874, l='MpServer', x=-519.50, y=35.00, z=967.50], EntityCreeper['Creeper'/51878, l='MpServer', x=-444.50, y=19.00, z=882.50], EntitySkeleton['Skeleton'/51877, l='MpServer', x=-438.50, y=19.00, z=880.50], EntityCow['Cow'/145, l='MpServer', x=-498.16, y=67.00, z=912.06], EntitySheep['Sheep'/146, l='MpServer', x=-488.53, y=70.00, z=900.34], EntityCow['Cow'/147, l='MpServer', x=-512.50, y=65.00, z=902.63], EntitySheep['Sheep'/148, l='MpServer', x=-494.56, y=68.00, z=900.34], EntitySheep['Sheep'/149, l='MpServer', x=-490.94, y=69.00, z=924.09], EntitySkeleton['Skeleton'/58393, l='MpServer', x=-480.50, y=36.00, z=917.50], EntityItem['item.item.fish.cod.raw'/51621, l='MpServer', x=-517.53, y=64.13, z=933.31], EntitySkeleton['Skeleton'/58407, l='MpServer', x=-507.50, y=37.00, z=954.50], EntitySkeleton['Skeleton'/51617, l='MpServer', x=-518.50, y=45.00, z=956.50], EntityEnderman['Enderman'/58408, l='MpServer', x=-548.50, y=11.00, z=864.50], EntitySpider['Spider'/58420, l='MpServer', x=-480.50, y=33.00, z=909.50], EntitySkeleton['Skeleton'/58419, l='MpServer', x=-497.00, y=38.00, z=948.56], EntityZombie['Zombie'/58429, l='MpServer', x=-506.44, y=38.00, z=939.97], EntityGolemBobber['entity.Thaumcraft.GolemBobber.name'/58447, l='MpServer', x=-517.78, y=63.90, z=930.09], EntityGolemBobber['entity.Thaumcraft.GolemBobber.name'/58444, l='MpServer', x=-518.47, y=63.90, z=928.13], EntityBat['Bat'/51661, l='MpServer', x=-504.73, y=24.65, z=869.46], EntityBat['Bat'/51660, l='MpServer', x=-484.38, y=16.00, z=882.48], EntityItem['item.item.arrow'/58459, l='MpServer', x=-483.56, y=68.13, z=897.16], EntityCreeper['Creeper'/51675, l='MpServer', x=-518.50, y=36.00, z=961.50], EntityItem['item.item.bone'/58460, l='MpServer', x=-482.94, y=68.13, z=897.19], EntitySpider['Spider'/58136, l='MpServer', x=-512.50, y=37.00, z=954.22], EntitySkeleton['Skeleton'/51680, l='MpServer', x=-491.50, y=16.00, z=924.50], EntityZombie['Zombie'/58139, l='MpServer', x=-470.50, y=12.00, z=938.50], EntityItem['item.item.fish.cod.raw'/58143, l='MpServer', x=-517.19, y=62.13, z=930.75], EntityBat['Bat'/58128, l='MpServer', x=-431.22, y=15.00, z=832.59], EntitySkeleton['Skeleton'/37614, l='MpServer', x=-5.79, y=-33.62, z=16.56], EntityBat['Bat'/58127, l='MpServer', x=-423.97, y=20.00, z=939.53], EntityItem['item.item.rottenFlesh'/58488, l='MpServer', x=-493.38, y=68.13, z=888.59]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:909)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.7.0_71, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 637485352 bytes (607 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xincgc -Xmx1g -Xms1g
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 95
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 Optifine OptiFine_1.7.10_HD_U_B4 27 mods loaded, 27 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.0.4.83} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.83-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Baubles{1.0.1.7} [Baubles] (Baubles-1.7.10-1.0.1.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Thaumcraft{4.2.0.1} [Thaumcraft] (Thaumcraft-1.7.10-4.2.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	VegeterianFood{1.2.0} [VegeterianFood] (VegeterianFood1.7.10-v1.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DamageIndicatorsMod{3.2.0} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	uncraftingTable{1.4.1} [Uncrafting Table] ([1.7.10]Uncrafting Table Mod v1.4.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1057-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BlockUtility{1.0.0} [Block Utility] (Block-Utility-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CarpentersBlocks{3.3.4.2} [Carpenter's Blocks] (Carpenter's Blocks v3.3.4.2 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	colourfulportalsmod{1.4.2} [Colourful Portals] (ColourfulPortals-1.4.2_for_1.7.X.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GalacticraftCore{3.0.8} [Galacticraft Core] (GalacticraftCore-1.7-3.0.8.258.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GalacticraftMars{3.0.8} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.8.258.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SteveCore{1.0.0} [Steve's Core] (More-Planet's-BETA-1.7.10-1.2.0-Pre-1-Dev.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MorePlanet{1.2.0} [More Planet's] (More-Planet's-BETA-1.7.10-1.2.0-Pre-1-Dev.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	cfm{3.4.7} [ง9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NBTEdit{1.7.2.2} [In-game NBTEdit] (NBTEdit_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ReiMinimap{1.7.10} [Rei's Minimap] (ReiMinimap-1.7.10-3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	chunkbase_slimemod_ssp{2.1} [Slime Mod (SSP)] (SlimeModSSP-1.7.10-2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SpecialArmor{1.7.10} [TeeLuk's SpecialArmor] (TLSpecialArmor-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: GeForce 9500 GT/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by wwrpg** [comment] 2015-05-08 05:19
I think this is a duplicate of #442

**Comment by Adaptivity** [comment] 2015-05-08 05:45
And possibly of #374

**Comment by Adaptivity** [comment] 2015-09-13 11:56
@Adubbz close.

**Closed** 2015-09-17 10:11 UTC
