### ISSUE TITLE
Still getting render error with Biomes O' Plenty 1.19.2-17.1.1.167

### ISSUE THREAD

**Issue by CToss** [Glitchfiend/BiomesOPlenty#2061] opened 2022-11-29 22:02 UTC
### What's the issue you encountered?

Updated to recent BoP beta build for server/client. Server console still outputting render error:

[minecraft/Util]: Detected setBlock in a far chunk [-20, -2], pos: BlockPos{x=-311, y=115, z=-19}, status: minecraft:features, currently generating: ResourceKey[minecraft:worldgen/placed_feature / biomesoplenty:flesh_tendon]

This is on 167

Happening in Erupting Inferno Biome

### How can the issue be reproduced?

Enter nether, at least as far as i can tell in Erupting Inferno Biome, on beta build still receiving same error

### Logs

https://gist.github.com/CToss/efe4b61d70bd412ce8ca5df4800a7c44

### Mod Version

17.1.1.167

**Comment by Adubbz** [comment] 2022-11-29 22:03
Duplicate of #2048

**Closed as completed by Adubbz** 2022-11-29 22:03 UTC
Labels: bug
