### ISSUE TITLE
blood bucket evaperates in the nether

### ISSUE THREAD

**Issue by Sinogard** [Glitchfiend/BiomesOPlenty#2242] opened 2024-07-21 18:07 UTC
### What's the issue you encountered?

seems like this may be unintended as you can find it in the nether naturally but you cant place it after picking it up in a bucket.

### How can the issue be reproduced?

get bucket, pick up blood, attempt to place in the nether. doesnt matter if you try to place it back where you got it or not it evaporates when placed.

### Logs

there is no error in the log

### Mod Version

21.0.0.12

**Comment by Forstride** [comment] 2024-07-21 18:50
Duplicate of #2161

**Closed as completed by Forstride** 2024-07-21 18:50 UTC
Labels: bug
