### ISSUE TITLE
BoP and Apotheosis crash when together on 31.2.0

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [Glitchfiend/BiomesOPlenty#1604] opened 2020-05-16 05:18 UTC
### How can the crash be reproduced?

Launch minecraft with bop 1.15.2-360, apotheosis 1.15.2 3.1.1, forge 31.2.0
crash

### Crash Report and Logs
https://pastebin.com/qE9unkc6

### Mod Version
bop 1.15.2-360, apotheosis 1.15.2 3.1.1, forge 31.2.0
crash</br>

**Comment by Adubbz** [comment] 2020-05-16 05:19
Duplicate of #1602

**Closed by Adubbz** 2020-05-16 05:19 UTC
Labels: crash
