### ISSUE TITLE
[1.7.10] Silty and sandy grass return wrong meta

### ISSUE THREAD

**Issue by tehFoxx0rz** [Glitchfiend/BiomesOPlenty#556] opened 2015-11-18 15:37 UTC
When using pick block on sandy grass or silty grass, it returns the meta above it.  Pick block on sandy grass returns silty grass, and pick block on silty grass returns...a glitch block which crashes the game (and can't be loaded again without, I'd presume, removing it without editing out of your player file).

**Comment by Adaptivity** [comment] 2016-01-03 08:48
Can't reproduce at all. What do you mean by "pick block"? Using silk touch? Which BoP version?

**Comment by Syndaryl** [comment] 2016-01-03 14:58
On 03/01/2016 3:48 AM, Anton wrote:
>
> Can't reproduce at all. What do you mean by "pick block"? Using silk 
> touch? Which BoP version?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Glitchfiend/BiomesOPlenty/issues/556#issuecomment-168479110>.
>

Pick Block is usually the middle-click :/

-- 
Emily Smirle - Gal Dynamo
<emily.smirle@gmail.com>

**Comment by Adaptivity** [comment] 2016-01-03 15:00
Already figured it. This is why I removed my comment :) Should be fixed soon.

**Comment by fewizz** [comment] 2016-01-03 21:54
Close this pls.

**Closed** 2016-01-04 13:21 UTC
